(function () {
  'use strict';

  /* ============================================================
     Motion Plus Corporation — lang.js
     EN / TH language toggle system
     ============================================================ */

  var T = {
    en: {
      /* ---------- Common (all pages) ---------- */
      'ann-text':           'Authorised Distributor &amp; After-Sales Service Provider for Industrial Chain Solutions',
      'ann-link':           'Enquire Now →',
      'nav-home':           'Home',
      'nav-about':          'About',
      'nav-portfolio':      'Portfolio',
      'nav-products':       'Our Products',
      'nav-contact':        'Contact',
      'nav-quote':          'Get a Quote',
      'btn-email':          'Email Us',
      'back-to-products':   'Back to Products',
      'footer-about-text':  'Authorised Distributor &amp; After-Sales Service Provider for Industrial Chain Solutions across Southeast Asia. Precision engineering, world-class brands.',
      'footer-solutions-h': 'Solutions',
      'footer-roller':      'Roller Chains',
      'footer-conveyor':    'Conveyor Chains',
      'footer-escalator':   'Escalator Chains',
      'footer-drive':       'Drive Chains',
      'footer-support':     'After-Sales Support',
      'footer-brands-h':    'Our Brands',
      'footer-company-h':   'Company',
      'footer-about-mpc':   'About MPC',
      'footer-portfolio':   'Portfolio',
      'footer-contact-us':  'Contact Us',
      'footer-get-quote':   'Get a Quote',
      'footer-contact-h':   'Contact',
      'footer-addr-lbl':    'Address',
      'footer-tel-lbl':     'Telephone',
      'footer-email-lbl':   'Email',
      'footer-hours-lbl':   'Business Hours',
      'footer-mon-fri':     'Mon – Fri',
      'footer-sat':         'Saturday',
      'footer-copyright':   '&copy; 2026 Motion Plus Corporation. All rights reserved.',
      'footer-copy':        '&copy; 2026 Motion Plus Corporation Co., Ltd. All rights reserved.',
      'footer-privacy':     'Privacy Policy',
      'footer-terms':       'Terms of Service',

      /* ---------- Index page ---------- */
      'hero-eyebrow':   'Industrial Chain Solutions',
      'hero-h1':        'Precision Chains.<br><span>World-Class</span> Performance.',
      'hero-sub':       'Motion Plus Corporation is your authorised distributor and after-sales service provider for premium industrial chain solutions across Southeast Asia.',
      'hero-btn-view':  'View Our Work',
      'hero-btn-quote': 'Get a Quote',
      'stat-years-lbl': 'Years Experience',
      'stat-brands-lbl':'Premium Brands',
      'stat-clients-lbl':'Clients Served',
      'stat-ind-lbl':   'Industries',
      'sbar-years':     'Years of Experience',
      'sbar-brands':    'Authorised Brands',
      'sbar-clients':   'Clients Served',
      'sbar-ind':       'Key Industries',
      'cert-iso':       'ISO Certified',
      'cert-dist':      'Authorised Distributor',
      'cert-as':        'After-Sales Service',
      'cert-sea':       'SEA Coverage',
      'esc-eyebrow':    'Proprietary Brand',
      'esc-h3':         'Motion Escalator',
      'esc-body':       "MPC's proprietary brand for precision escalator step chains and drive chains, engineered to EN 115 and ASME A17.1 standards. Trusted by transit authorities and commercial developers across Southeast Asia.",
      'esc-btn':        'Get Product Details',
      'brands-eyebrow': 'Brand Partners',
      'brands-h2':      'Our Authorised Brands',
      'brands-body':    'We are the authorised distributor for ten world-class industrial chain manufacturers, bringing global engineering standards to your operations.',
      'commit-eyebrow': 'Our Promise',
      'commit-h2':      'Our Commitment',
      'commit-quote':   'We provide after-sales support by maintaining close communication with our customers and suppliers. We coordinate with manufacturers to resolve issues efficiently — without requiring international site visits.',
      'ind-eyebrow':    'Sectors We Serve',
      'ind-h2':         'Our Specialized Industries',
      'ind-body':       'From heavy steel processing to food-grade palm oil production, our chain solutions are proven across the most demanding industrial environments.',
      'steel-h3':       'Steel Industry',
      'steel-p':        'High-load conveyor and drive chains for steel mills and processing facilities.',
      'cement-h3':      'Cement Industry',
      'cement-p':       'Abrasion-resistant chains for kiln drives and bulk cement handling systems.',
      'palm-h3':        'Palm Oil Industry',
      'palm-p':         'Food-grade and corrosion-resistant chains for palm oil milling and processing.',
      'sugar-h3':       'Sugar Industry',
      'sugar-p':        'Heavy-duty cane carrier and conveyor chains engineered for sugar mill environments.',
      'promise-eyebrow':'Our Promise',
      'promise-h2':     'Built on Precision,<br>Driven by Excellence',
      'promise-p':      'We conduct strict quality checks and provide reliable after-sales service. We coordinate with manufacturers and suppliers to resolve any issues efficiently, without requiring international site visits.',
      'promise-btn':    'Learn More About Us',
      'enq-eyebrow':    'Stay Connected',
      'enq-h2':         'Ready to Upgrade Your Chain Systems?',
      'enq-p':          'Email or call us directly — our team responds within one business day.',
      'enq-email':      'Email Us →',
      'enq-call':       'Call 02 286-5656',

      /* ---------- About page ---------- */
      'abt-eyebrow':        'Our Company',
      'abt-h1':             'About MPC',
      'abt-sub':            'Precision Engineering. Global Standards.',
      'abt-story-eyebrow':  'Our Story',
      'abt-story-h2':       'Built on Precision,<br>Driven by Excellence',
      'abt-story-p1':       'Motion Plus Corporation was founded with a singular mission: to bring world-class industrial chain technology to the rapidly growing manufacturing and processing sectors of Southeast Asia.',
      'abt-story-p2':       'As an authorised distributor for ten internationally recognised chain brands, MPC provides more than just products — we deliver precision-engineered solutions, reliable after-sales support, and long-term partnerships that keep our clients\' operations running at peak performance.',
      'abt-story-p3':       'Our team works alongside clients from product delivery through to ongoing maintenance and support.',
      'abt-found-eyebrow':  'Who We Are',
      'abt-found-h2':       'Our Foundation &amp; Philosophy',
      'abt-found-body':     'Established in <strong>2004</strong>, Motion Plus Corporation has spent over two decades building a reputation for precision, reliability, and genuine partnership across Southeast Asia\'s most demanding industries.',
      'abt-key-h3':         'Key to Success',
      'abt-key-p':          'We focus on delivering reliable, high-value solutions that combine quality, efficiency, and long-term performance to support a wide range of industrial applications.',
      'abt-phil-h3':        'Company Philosophy',
      'abt-phil-p':         'We guarantee the quality of our selective product range through a long-term commitment to excellence, fostering a collaborative environment dedicated to total customer satisfaction.',
      'abt-commit-h3':      'Our Commitment',
      'abt-commit-p':       'We maintain close communication with our customers and suppliers, coordinating with manufacturers to ensure any issues are resolved efficiently and professionally.',
      'abt-exp-h3':         'Experience &amp; Company Profile',
      'abt-as-eyebrow':     'After-Sales Service',
      'abt-as-h2':          'After-Sales Support You Can Rely On',
      'abt-as-p':           'We provide after-sales support by maintaining close communication with our customers and suppliers to help resolve any issues efficiently. While we supply across overseas markets, we do not send engineers to international sites. Instead, we assist by coordinating with manufacturers and suppliers to ensure problems are properly addressed and resolved as quickly as possible.',
      'abt-brands-eyebrow': 'Brand Partners',
      'abt-brands-h2':      'Our Authorised Brands',
      'abt-brands-p':       'We are the authorised distributor for ten world-class industrial chain manufacturers.',
      'abt-cta-h2':         'Ready to Work with MPC?',
      'abt-cta-p':          'Contact our team to discuss your requirements. We\'ll find the right chain solution for your application.',
      'abt-cta-btn':        'Get in Touch',
      'since-years-lbl':    'Years of Industry Excellence',
      'since-eng-lbl':      'Engineers &amp; Professionals',
      'since-clients-lbl':  'Clients Served',
      'since-brands-lbl':   'Global Brand Partners',
      'since-tagline':      "Southeast Asia's Trusted Industrial Chain Partner",
      'abt-exp-headline':   '20+ Years of Industrial Excellence',
      'abt-exp-body':       'Since 2004, we have delivered world-class chain solutions across Southeast Asia, connecting clients with leading international manufacturers and providing responsive local support.',
      'abt-exp-li1':        'Global Reach — Elite partnerships with international chain manufacturers',
      'abt-exp-li2':        'Expert Team — 35+ engineers and industry professionals',
      'abt-exp-li3':        'Proven Track Record — Steel, Sugar, Cement, and Food &amp; Beverage sectors',
      'abt-val-eyebrow':    'What Drives Us',
      'abt-val-h2':         'Our Core Values',
      'abt-val-intro':      'Three principles guide every decision and partnership at Motion Plus Corporation.',
      'abt-val-prec-h3':    'Precision',
      'abt-val-prec-p':     'Every specification matters. We apply exacting standards to product selection and quality assurance to ensure reliable performance in critical systems.',
      'abt-val-rel-h3':     'Reliability',
      'abt-val-rel-p':      'Our chains come from manufacturers with proven track records. When issues arise, our after-sales team coordinates swiftly to minimise downtime.',
      'abt-val-part-h3':    'Partnership',
      'abt-val-part-p':     'We invest in long-term relationships — understanding your processes and goals so we can be a genuine partner in your success, not just a supplier.',
      'abt-as-li1':         'Direct communication and issue coordination support',
      'abt-as-li2':         'Collaboration with manufacturers and principal suppliers',
      'abt-as-li3':         'Efficient resolution without international site visits',
      'abt-as-btn':         'Contact Our Team',
      'abt-partners-p':     'Ten world-class chain manufacturers — one trusted source.',
      'abt-cta-eyebrow':    'Get Started',
      'abt-view-work':      'View Our Work',

      /* ---------- Product Representation (About page) ---------- */
      'prod-rep-eyebrow':  'What We Supply',
      'prod-rep-h2':       'Our Product Representation',
      'prod-rep-intro':    'Precision-engineered solutions from globally recognised manufacturers — selected for quality, reliability, and proven performance across Southeast Asia\'s most demanding industries.',
      'prod-hs-origin':    'China',
      'prod-hs-name':      'HS Chains',
      'prod-hs-desc':      'Premium roller and conveyor chains manufactured to exacting tolerances for high-load industrial applications.',
      'prod-db-origin':    'South Korea',
      'prod-db-name':      'Dong Bo Chain',
      'prod-db-desc':      'World-class precision chains engineered for performance-critical machinery across steel, cement, and food processing industries.',
      'prod-uno-origin':   'Standard Series',
      'prod-uno-name':     'UNO Roller Chains',
      'prod-uno-desc':     'Reliable standard transmission chains delivering consistent value-to-performance across general industrial conveying applications.',
      'prod-dia-origin':   'USA',
      'prod-dia-name':     'Diamond Chain',
      'prod-dia-desc':     'High-integrity drive and conveyor chains for mission-critical applications, trusted by the world\'s most demanding operations since 1890.',
      'prod-iwis-origin':  'Germany',
      'prod-iwis-name':    'IWIS',
      'prod-iwis-desc':    'Precision-engineered drive chains with ultra-fine tolerances and extended service life — the benchmark for automated, high-speed systems.',
      'prod-kmh-origin':   'Germany',
      'prod-kmh-name':     'KMH',
      'prod-kmh-desc':     'Industrial-grade standard and custom tube solutions engineered for precise fit, structural integrity, and consistent industrial performance.',
      'prod-belt-origin':  'Industrial Series',
      'prod-belt-name':    'Industrial Belts',
      'prod-belt-desc':    'High-durability power transmission and conveyor belts selected for continuous industrial operation across demanding process environments.',
      'prod-bear-origin':  'Multi-Brand',
      'prod-bear-name':    'Genuine Bearings',
      'prod-bear-desc':    'Authentic bearings from globally recognised manufacturers — fully traceable, quality-assured, and specified for long-term operational reliability.',
      'prod-rep-btn':      'Request a Product Catalogue',

      /* ---------- Portfolio page ---------- */
      'port-eyebrow':  'Our Work',
      'port-h1':       'Our Projects',
      'port-sub':      'Industrial chain solutions across demanding sectors.',
      'filt-all':      'All',
      'filt-steel':    'Steel',
      'filt-cement':   'Cement',
      'filt-palm':     'Palm Oil',
      'filt-sugar':    'Sugar',
      'filt-chains':   'Chains',
      'port-cta-h2':   'Have a Project in Mind?',
      'port-cta-p':    'Tell us about your application and our team will recommend the right chain solution.',
      'port-cta-btn1': 'Start a Conversation',
      'port-cta-btn2': 'Learn About MPC',
      'port-dl-eyebrow':      'Resources',
      'port-dl-h2':           'Download Our Resources',
      'port-dl-intro':        'Access our latest product brochure and company profile for detailed specifications and a full overview of our solutions.',
      'port-dl-brochure':     'Download Brochure',
      'port-dl-brochure-sub': 'Product overview &amp; specifications',
      'port-dl-profile':      'Download Company Profile',
      'port-dl-profile-sub':  'Company overview (Thai)',

      /* ---------- Contact page ---------- */
      'cont-eyebrow':    'Reach Out',
      'cont-h1':         'Get In Touch',
      'cont-sub':        "Let's find the right solution for your industry.",
      'trust-resp':      'Response Time',
      'trust-coverage':  'Regional Coverage',
      'trust-brands':    'Authorised Brands',
      'trust-clients':   'Clients Served',
      'cont-how-eyebrow':'How to Reach Us',
      'cont-h2':         'Contact Information',
      'cont-intro':      'Reach us directly — our team is ready to assist with product enquiries, after-sales support, and general information.',
      'cont-email-lbl':  'Email',
      'cont-email-sub':  'We respond within one business day',
      'cont-phone-lbl':  'Phone',
      'cont-phone-sub':  'Available during business hours',
      'cont-fax-lbl':    'Fax',
      'cont-fax-sub':    'For document transmission',
      'cont-addr-lbl':   'Address',
      'cont-hours-lbl':  'Business Hours',
      'cont-social-lbl': 'Connect With Us',
      'cont-map-eyebrow':  'Our Location',
      'cont-map-h2':       'Find Us',
      'cont-map-btn':      'Send Us an Email',
      'cont-map-btn-gmaps':'Open in Google Maps',
      'nav-email-cta':     'Send Us an Email',
      'prod-eyebrow':      'What We Supply',
      'prod-h1':           'Our Products',
      'prod-sub':          'Precision-engineered solutions for every industrial application.',
      'prod-cat-eyebrow':  'Product Range',
      'prod-cat-h2':       'Browse Our Catalogue',
      'prod-cat-intro':    'Click any category to explore available products. Contact our team for specifications, pricing, or custom solutions.',
      'prod-cta-h':        'Need a specific product?',
      'prod-cta-p':        'Contact our team for full specifications, datasheets, and pricing.',
      'prod-cta-btn':      'Get a Quote',
      'prod-cta-email':    'Email Us',

      /* ======================================================
         CEMENT INDUSTRY CHAINS PAGE
      ====================================================== */
      'cem-eyebrow':      'Industry-Specific Chains',
      'cem-h1':           '<em>Cement</em> Industry Chains',
      'cem-sub':          'Reclaimer · Hoister · Apron Conveyor · Slide Fastener Machine Chains',
      'cem-badge-iso':    'ISO9001 Assured',
      'cem-badge-severe': 'Severe Conditions',
      'cem-badge-heat':   'High Temperature',
      'cem-badge-proven': 'Proven Quality',
      'cem-bc-cat':       'Industry-Specific Chains',
      'cem-bc-active':    'Cement Industry Chains',
      'cem-brand-tag':    'HS Chain · Cement Industry',
      'cem-s1-eyebrow':   'Product Overview',
      'cem-s1-h2':        'Cement Industry Chains',
      'cem-s1-sub':       'Specially designed for severe cement plant conditions',
      'cem-cbadge-iso':   'ISO9001',
      'cem-cbadge1':      'Reclaimer Chain',
      'cem-cbadge2':      'Hoister Chain',
      'cem-cbadge3':      'Apron Conveyor',
      'cem-cbadge4':      'High Temperature',
      'cem-s1-p1':        'With years of experience and persistent improvement, we can provide the reclaimer chain, hoister chain, apron conveyor chain, and slide fastener machine chain, specially designed for the severe conditions of cement industry.',
      'cem-s1-p2':        'Each link of the production process is under the close monitor of ISO9001 quality assurance system, and the high quality along with variety of products are used and praised by most of well-known cement manufacturers.',
      'cem-iso-title':    'ISO9001 Quality Assurance',
      'cem-iso-body':     'Every step of the production process is monitored under the ISO9001 quality assurance system to ensure consistent, world-class chain quality.',
      'cem-s2-eyebrow':   'Product Range',
      'cem-s2-h2':        'Cement Industry Chain Types',
      'cem-s2-intro':     'A comprehensive range of chains purpose-built for every stage of cement production — from raw material reclaiming to finished product handling.',
      'cem-s3-eyebrow':   'Engineering Excellence',
      'cem-s3-h2':        'Why Choose Our Cement Industry Chains?',
      'cem-s3-intro':     'Engineered specifically for the most demanding conditions found in modern cement manufacturing facilities worldwide.',
      'cem-step1-title':  'Reclaimer Chain',
      'cem-step1-body':   'Purpose-built reclaimer chains for raw material stockpile recovery — handling continuous abrasive loads with minimal maintenance intervals.',
      'cem-step2-title':  'Hoister Chain',
      'cem-step2-body':   'Heavy-duty hoister chains engineered for vertical lifting applications in cement plants — high tensile strength with precision pitch consistency.',
      'cem-step3-title':  'Apron Conveyor Chain',
      'cem-step3-body':   'Robust apron conveyor chains for bulk material transport — designed to withstand impact, abrasion, and high-temperature environments.',
      'cem-step4-title':  'Slide Fastener Machine Chain',
      'cem-step4-body':   'Precision slide fastener machine chains for packaging and handling stages — maintaining accuracy under continuous-duty operation.',
      'cem-step5-title':  'ISO9001 Quality System',
      'cem-step5-body':   'Every production link is monitored under the ISO9001 quality assurance system — trusted and praised by well-known cement manufacturers worldwide.',
      'cem-step6-title':  'Full MPC Support',
      'cem-step6-body':   'Technical consultation, application-specific chain selection, and after-sales support across Southeast Asia through Motion Plus Corporation.',
      'cem-cta-h':        'Need cement industry chain solutions?',
      'cem-cta-p':        'Contact our team for technical consultation, product specifications, and a customised quotation for your cement plant requirements.',

      /* ======================================================
         BEARING PAGE
      ====================================================== */
      'bear-eyebrow':     'Other Products',
      'bear-h1':          '<em>Bearing</em>',
      'bear-sub':         'Ball Bearings · Roller Bearings · Tapered · Cylindrical — World-Class Brands',
      'bear-badge1':      'Deep Groove',
      'bear-badge2':      'Roller Bearings',
      'bear-badge3':      'World-Class Brands',
      'bear-badge4':      'All Industries',
      'bear-bc-cat':      'Other',
      'bear-bc-active':   'Bearing',
      'bear-brand-tag':   'MPC · Other Products',
      'bear-s1-eyebrow':  'Product Overview',
      'bear-s1-h2':       'Bearing',
      'bear-s1-sub':      'World-class bearings for every industrial application',
      'bear-cbadge1':     'Deep Groove Ball Bearing',
      'bear-cbadge2':     'Cylindrical Roller Bearing',
      'bear-cbadge3':     'Tapered Roller Bearing',
      'bear-cbadge4':     'Angular Contact',
      'bear-cbadge5':     'Spherical Roller',
      'bear-cbadge6':     'Linear Bearings',
      'bear-s1-p1':       'Motion Plus Corporation supplies precision bearings from the world\'s most trusted manufacturers. Whether you need standard deep groove ball bearings for light-duty applications or heavy-load cylindrical and tapered roller bearings for demanding industrial environments, our range covers every requirement.',
      'bear-s1-p2':       'We stock and source bearings from SKF, FAG, TIMKEN, NTN, NSK, THK, Koyo, INA, McGILL, NB, and more — with technical consultation available to help you select the right bearing type, size, and specification for your application.',
      'bear-iso-title':   'Genuine Authorised Products',
      'bear-iso-body':    'All bearings supplied by Motion Plus Corporation are genuine products sourced directly from authorised distribution channels — ensuring full manufacturer quality guarantees and traceability.',
      'bear-s2-eyebrow':  'Product Range',
      'bear-s2-h2':       'Products',
      'bear-s2-intro':    'A comprehensive range of precision bearings — from miniature ball bearings to heavy-duty industrial roller bearings — covering all sizes and load requirements.',
      'bear-s3-eyebrow':  'Authorised Distribution',
      'bear-s3-h2':       'Brands We Offer',
      'bear-s3-intro':    'We supply genuine bearings from the world\'s leading manufacturers — trusted by engineers across Southeast Asia\'s most demanding industries.',
      'bear-s4-eyebrow':  'Why Choose MPC Bearings',
      'bear-s4-h2':       'Precision. Reliability. Coverage.',
      'bear-s4-intro':    'From miniature bearings to large industrial units — every type supplied with genuine quality assurance from world-class manufacturers.',
      'bear-step1-title': 'Deep Groove Ball Bearings',
      'bear-step1-body':  'The most widely used bearing type — available open, shielded (ZZ), or sealed (2RS) across all standard bore sizes and series.',
      'bear-step2-title': 'Cylindrical Roller Bearings',
      'bear-step2-body':  'High radial load capacity for heavy-duty industrial applications — single-row, double-row, and four-row configurations available.',
      'bear-step3-title': 'Tapered Roller Bearings',
      'bear-step3-body':  'Handle combined radial and axial loads — ideal for gearboxes, vehicle axles, and heavy-duty rotating equipment.',
      'bear-step4-title': 'Linear &amp; Motion Bearings',
      'bear-step4-body':  'THK and NB linear guides, ball splines, and linear bushings for precision linear motion in automated and CNC machinery.',
      'bear-step5-title': 'Angular Contact &amp; Spherical',
      'bear-step5-body':  'Angular contact ball bearings for high-speed spindle applications; spherical roller bearings for misalignment tolerance in heavy machinery.',
      'bear-step6-title': 'Full MPC Support',
      'bear-step6-body':  'Technical bearing selection, cross-referencing, and after-sales support across Southeast Asia — contact our team for specifications and pricing.',
      'bear-cta-h':       'Need bearings for your application?',
      'bear-cta-p':       'Contact our team for technical selection, cross-referencing, datasheets, and competitive pricing on any bearing type or brand.',

      /* ======================================================
         BELT PAGE
      ====================================================== */
      'belt-eyebrow':    'Other Products',
      'belt-h1':         '<em>Belt</em>',
      'belt-bc-cat':     'Other',
      'belt-bc-active':  'Belt',
      'belt-s1-eyebrow': 'Product Range',
      'belt-s1-h2':      'Belt',
      'belt-s2-eyebrow': 'Authorised Distribution',
      'belt-s2-h2':      'Belt Brands We Offer',
      'belt-cta-h':      'Need belts for your application?',
      'belt-cta-p':      'Contact our team for specifications, cross-referencing, and pricing on any belt type or brand.',

      /* ======================================================
         COUPLING PAGE
      ====================================================== */
      'cpl-eyebrow':    'Other Products',
      'cpl-h1':         '<em>Coupling</em>',
      'cpl-bc-cat':     'Other',
      'cpl-bc-active':  'Coupling',
      'cpl-s1-eyebrow': 'Product Range',
      'cpl-s1-h2':      'Coupling',
      'cpl-cta-h':      'Need couplings for your application?',
      'cpl-cta-p':      'Contact our team for specifications, selection support, and pricing on any coupling type.',

      /* ======================================================
         OIL SEAL PAGE
      ====================================================== */
      'os-eyebrow':    'Other Products',
      'os-h1':         '<em>Oil Seal</em>',
      'os-bc-cat':     'Other',
      'os-bc-active':  'Oil Seal',
      'os-s1-eyebrow': 'Product Range',
      'os-s1-h2':      'Oil Seal',
      'os-cta-h':      'Need oil seals for your application?',
      'os-cta-p':      'Contact our team for specifications, sizing, and pricing on any oil seal type.',

      /* ======================================================
         PE-1000 PAGE
      ====================================================== */
      'pe-eyebrow':    'Other Products',
      'pe-h1':         '<em>PE-1000</em>',
      'pe-bc-cat':     'Other',
      'pe-bc-active':  'PE-1000',
      'pe-s1-eyebrow': 'Product Range',
      'pe-s1-h2':      'PE-1000',
      'pe-cta-h':      'Need PE-1000 components for your application?',
      'pe-cta-p':      'Contact our team for specifications, custom sizing, and pricing on PE-1000 products.',

      /* ======================================================
         SPROCKETS & PULLEY PAGE
      ====================================================== */
      'sp-eyebrow':    'Drive Components',
      'sp-h1':         '<em>Sprockets</em> &amp; Pulley',
      'sp-bc-cat':     'Sprockets &amp; Pulley',
      'sp-bc-active':  'Sprockets &amp; Pulley',
      'sp-s1-eyebrow': 'Product Range',
      'sp-s1-h2':      'Sprockets &amp; Pulley',
      'sp-cta-h':      'Need sprockets or pulleys for your application?',
      'sp-cta-p':      'Contact our team for technical specifications, custom tooth profiles, and competitive pricing.',

      /* ======================================================
         PALM OIL CHAINS PAGE
      ====================================================== */
      'palm-pg-eyebrow':   'Industry-Specific Chains',
      'palm-pg-h1':        'Palm Oil <em>Industry</em>',
      'palm-pg-sub':       'Hollow Pin · Solid Pin · Connecting Link Chains for Palm Oil Production',
      'palm-bc-cat':       'Industry-Specific Chains',
      'palm-bc-active':    'Palm Oil Industry',
      'palm-s1-eyebrow':   'Product Overview',
      'palm-s1-h2':        'Palm Oil Industry Chains',
      'palm-s1-p1':        'The palm oil chain is developed based on our applied research, focusing on improving reliability and performance in palm oil processing. Our chains are engineered for the demanding requirements of palm oil squeezing production lines — precision-finished, heat-treated, and pre-oiled for immediate deployment.',
      'palm-s2-eyebrow':   'Product Range',
      'palm-s2-h2':        'Palm Oil Chain Products',
      'palm-cta-h':        'Need palm oil industry chain solutions?',
      'palm-cta-p':        'Contact our team for technical consultation, product specifications, and a customised quotation for your palm oil plant requirements.',

      /* ======================================================
         KMH CONVEYOR PIPE PAGE
      ====================================================== */
      'kmh-pg-eyebrow':   'KMH Products',
      'kmh-pg-h1':        '<em>KMH</em> Conveyor Pipe',
      'kmh-bc-cat':       'KMH',
      'kmh-bc-active':    'Conveyor Pipe',
      'kmh-s1-eyebrow':   'KMH · Pipe Systems',
      'kmh-s1-h2':        'KMH Conveyor Pipe',
      'kmh-std-label':    'Standard Products',
      'kmh-std-heading':  'Standard Products (High Performance Pipe Systems):<br>From the KMH-Modular Construction Set',
      'kmh-std-body':     'The modular system of our standard products includes thousands of perfectly coordinated products. It is flexible and easy to manage – select the required components, interconnect them, and you can quickly and easily implement complex installations.',
      'kmh-spc-label':    'Special Productions',
      'kmh-spc-heading':  'Special Productions (Custom-Made Parts):<br>A Speciality of KMH',
      'kmh-spc-body':     'Whether modified standard products from the catalogue or new developments: Where the standard system is not enough, we have "SPECIALIZED" in individual solutions. KMH special productions are produced according to your specifications and requirements and compatible with standard systems.',
      'kmh-s2-eyebrow':   'Product Range',
      'kmh-s2-h2':        'KMH Conveyor Pipe Systems',
      'kmh-s3-eyebrow':   'Download Catalogue Below',
      'kmh-s3-h2':        'KMH Product Catalogue',
      'kmh-cat-title':    'KMH Produktkatalog 2023',
      'kmh-cat-meta':     'High Performance Pipe Systems · Custom Solutions',
      'kmh-cat-btn':      'Download KMH Catalogue Here',
      'kmh-cta-h':        'Need a custom KMH pipe solution?',
      'kmh-cta-p':        'Contact our team for project specifications, custom designs, and full pricing.',

      /* ======================================================
         PRODUCTS PAGE — Catalogue (accordion)
      ====================================================== */
      'prod-view-link':    'View Products',
      /* Category titles */
      'prod-cat1-title':   'Standard Roller Chains',
      'prod-cat1-count':   '3 brands',
      'prod-cat2-title':   'Conveyor &amp; Transport Chains',
      'prod-cat2-count':   '2 brands',
      'prod-cat3-title':   'Heavy-Duty Forged Chains',
      'prod-cat3-count':   '1 type',
      'prod-cat4-title':   'Industry-Specific Chains',
      'prod-cat4-count':   '3 sectors',
      'prod-cat5-title':   'Sprockets &amp; Pulley',
      'prod-cat5-count':   '1 type',
      'prod-cat6-title':   'Other',
      'prod-cat6-count':   '5 types',
      'prod-cat7-title':   'KMH',
      'prod-cat7-count':   '1 type',
      /* Sub-card names & descriptions */
      'prd-uno-name':      'UNO Chains',
      'prd-uno-desc':      'ISO 9001 certified. A &amp; B series, single and multi-strand. Cost-efficient with premium performance.',
      'prd-db-name':       'Dongbo Chains',
      'prd-db-desc':       'ANSI standard roller chains — single, double &amp; triple strand. 45+ years Korean manufacturing.',
      'prd-iwis-rl-name':  'Iwis Chains',
      'prd-iwis-rl-desc':  'German precision roller chains — simplex &amp; duplex, ISO 606, acoustically optimised for high-speed drives.',
      'prd-iwis-cv-name':  'Iwis Conveyor Chains',
      'prd-iwis-cv-desc':  'Attachment, double-pitch, side-bow, and hollow-pin variants for complex conveyor systems.',
      'prd-hs-cv-name':    'HS Conveyor Chains',
      'prd-hs-cv-desc':    'Light-load to heavy-load conveyor chains for streamlining material transport in various industrial fields.',
      'prd-forged-name':   'Forged Chain TRIO / Forged Chain UNO',
      'prd-forged-desc':   'Top quality heavy-duty forged chains — TRIO (P.102 mm) and UNO (P.142 mm) — for steel mills, cement plants &amp; animal feed mills.',
      'prd-cement-name':   'Cement Industry',
      'prd-cement-desc':   'Reclaimer, hoister, apron conveyor &amp; slide fastener machine chains — ISO9001 assured for severe cement conditions.',
      'prd-sugar-name':    'Sugar Mill Industry',
      'prd-sugar-desc':    'Transmission, hoisting and conveying chains for sugar production — bagasse feeder, O-chain, bush chain and more for the full milling process.',
      'prd-palm-name':     'Palm Oil Industry',
      'prd-palm-desc':     'Hollow pin, solid pin and connecting link chains engineered for palm oil squeezing production lines — precision-finished, heat-treated and pre-oiled.',
      'prd-sp-name':       'Sprockets &amp; Pulley',
      'prd-sp-desc':       'Standard &amp; custom sprockets and pulleys — roller chain sprockets, timing pulleys, and heavy-duty drive components.',
      'prd-bearing-name':  'Bearing',
      'prd-bearing-desc':  'SKF, FAG, TIMKEN, NSK, NTN, Koyo &amp; more — deep groove ball, cylindrical roller, tapered roller and linear bearings.',
      'prd-belt-name':     'Belt',
      'prd-belt-desc':     'V-belts, timing belts, and flat belts for industrial power transmission.',
      'prd-coupling-name': 'Coupling',
      'prd-coupling-desc': 'Jaw, flexible, chain, and rigid couplings for shaft connection solutions.',
      'prd-oilseal-name':  'Oil Seal',
      'prd-oilseal-desc':  'Rotary shaft and industrial oil seals for reliable sealing under demanding conditions.',
      'prd-pe1000-name':   'PE-1000',
      'prd-pe1000-desc':   'High-density polyethylene wear strips, guide rails, and custom components.',
      'prd-kmhpipe-name':  'Conveyor Pipe',
      'prd-kmhpipe-desc':  'KMH enclosed pipe conveyor systems, tracks, and components for dust-free bulk material handling.',
      /* ---------- Distributor Brands section ---------- */
      'distrib-eyebrow': 'Distribution Portfolio',
      'distrib-h2':      'Distributor Brands',
      'distrib-body':    'Beyond our authorised brands, we distribute additional world-class industrial products to serve the full spectrum of your manufacturing needs.',

      /* ---------- Our House Brand section ---------- */
      'hb-eyebrow':      'Proprietary Products',
      'hb-h2':           'Our House Brand',
      'hb-body':         'Precision-engineered chains bearing the MPC stamp of quality — our proprietary brands engineered for the most demanding heavy-duty applications.',
      'hb-view-btn':     'View Products',
      'hb-brochure-btn': 'Download Brochure',

      /* Footer badges */
      'footer-badge-iso':  'ISO',
      'footer-badge-auth': 'Authorised',
      'footer-badge-sea':  'SEA'
    },

    /* ============================================================
       THAI TRANSLATIONS
    ============================================================ */
    th: {
      /* ---------- Common (all pages) ---------- */
      'ann-text':           'ผู้จัดจำหน่ายที่ได้รับอนุญาต &amp; ผู้ให้บริการหลังการขายสำหรับโซลูชันโซ่อุตสาหกรรม',
      'ann-link':           'สอบถามข้อมูล →',
      'nav-home':           'หน้าหลัก',
      'nav-about':          'เกี่ยวกับเรา',
      'nav-portfolio':      'ผลงาน',
      'nav-products':       'สินค้าของเรา',
      'nav-contact':        'ติดต่อเรา',
      'nav-quote':          'ขอใบเสนอราคา',
      'btn-email':          'ส่งอีเมลหาเรา',
      'back-to-products':   'กลับไปยังสินค้า',
      'footer-about-text':  'ผู้จัดจำหน่ายที่ได้รับอนุญาต &amp; ผู้ให้บริการหลังการขายสำหรับโซลูชันโซ่อุตสาหกรรมทั่วเอเชียตะวันออกเฉียงใต้ วิศวกรรมที่แม่นยำ แบรนด์ระดับโลก',
      'footer-solutions-h': 'โซลูชัน',
      'footer-roller':      'โซ่ลูกกลิ้ง',
      'footer-conveyor':    'โซ่ลำเลียง',
      'footer-escalator':   'โซ่บันไดเลื่อน',
      'footer-drive':       'โซ่ขับเคลื่อน',
      'footer-support':     'บริการหลังการขาย',
      'footer-brands-h':    'แบรนด์ของเรา',
      'footer-company-h':   'บริษัท',
      'footer-about-mpc':   'เกี่ยวกับ MPC',
      'footer-portfolio':   'ผลงาน',
      'footer-contact-us':  'ติดต่อเรา',
      'footer-get-quote':   'ขอใบเสนอราคา',
      'footer-contact-h':   'ติดต่อ',
      'footer-addr-lbl':    'ที่อยู่',
      'footer-tel-lbl':     'โทรศัพท์',
      'footer-email-lbl':   'อีเมล',
      'footer-hours-lbl':   'เวลาทำการ',
      'footer-mon-fri':     'จ. – ศ.',
      'footer-sat':         'เสาร์',
      'footer-copyright':   '&copy; 2026 บริษัท โมชั่น พลัส คอร์ปอเรชั่น จำกัด สงวนลิขสิทธิ์',
      'footer-copy':        '&copy; 2026 บริษัท โมชั่น พลัส คอร์ปอเรชั่น จำกัด สงวนลิขสิทธิ์',
      'footer-privacy':     'นโยบายความเป็นส่วนตัว',
      'footer-terms':       'ข้อกำหนดการใช้บริการ',

      /* ---------- Index page ---------- */
      'hero-eyebrow':   'โซลูชันโซ่อุตสาหกรรม',
      'hero-h1':        'โซ่ที่แม่นยำ<br><span>ประสิทธิภาพ</span>ระดับโลก',
      'hero-sub':       'บริษัท โมชั่น พลัส คอร์ปอเรชั่น คือผู้จัดจำหน่ายที่ได้รับอนุญาตและผู้ให้บริการหลังการขายสำหรับโซลูชันโซ่อุตสาหกรรมพรีเมียมทั่วเอเชียตะวันออกเฉียงใต้',
      'hero-btn-view':  'ดูผลงานของเรา',
      'hero-btn-quote': 'ขอใบเสนอราคา',
      'stat-years-lbl': 'ปีแห่งประสบการณ์',
      'stat-brands-lbl':'แบรนด์พรีเมียม',
      'stat-clients-lbl':'ลูกค้าที่ให้บริการ',
      'stat-ind-lbl':   'อุตสาหกรรม',
      'sbar-years':     'ปีแห่งประสบการณ์',
      'sbar-brands':    'แบรนด์ที่ได้รับอนุญาต',
      'sbar-clients':   'ลูกค้าที่ให้บริการ',
      'sbar-ind':       'อุตสาหกรรมหลัก',
      'cert-iso':       'ได้รับการรับรอง ISO',
      'cert-dist':      'ผู้จัดจำหน่ายที่ได้รับอนุญาต',
      'cert-as':        'บริการหลังการขาย',
      'cert-sea':       'ครอบคลุม SEA',
      'esc-eyebrow':    'แบรนด์ของบริษัท',
      'esc-h3':         'Motion Escalator',
      'esc-body':       'แบรนด์ของ MPC สำหรับโซ่ขั้นบันไดเลื่อนและโซ่ขับเคลื่อนที่แม่นยำ ออกแบบตามมาตรฐาน EN 115 และ ASME A17.1 ได้รับความไว้วางใจจากหน่วยงานขนส่งและนักพัฒนาอสังหาริมทรัพย์ทั่วเอเชียตะวันออกเฉียงใต้',
      'esc-btn':        'ขอข้อมูลสินค้า',
      'brands-eyebrow': 'พันธมิตรแบรนด์',
      'brands-h2':      'แบรนด์ที่ได้รับอนุญาต',
      'brands-body':    'เราเป็นผู้จัดจำหน่ายที่ได้รับอนุญาตสำหรับผู้ผลิตโซ่อุตสาหกรรมระดับโลกสิบราย นำมาตรฐานวิศวกรรมระดับสากลสู่การดำเนินงานของคุณ',
      'commit-eyebrow': 'คำมั่นสัญญาของเรา',
      'commit-h2':      'ความมุ่งมั่นของเรา',
      'commit-quote':   'เราให้บริการหลังการขายโดยรักษาการสื่อสารอย่างใกล้ชิดกับลูกค้าและซัพพลายเออร์ เราประสานงานกับผู้ผลิตเพื่อแก้ไขปัญหาอย่างมีประสิทธิภาพ โดยไม่จำเป็นต้องส่งวิศวกรไปยังไซต์งานในต่างประเทศ',
      'ind-eyebrow':    'ภาคส่วนที่เราให้บริการ',
      'ind-h2':         'อุตสาหกรรมเฉพาะทางของเรา',
      'ind-body':       'ตั้งแต่การแปรรูปเหล็กหนักไปจนถึงการผลิตน้ำมันปาล์มเกรดอาหาร โซลูชันโซ่ของเราได้รับการพิสูจน์แล้วในสภาพแวดล้อมอุตสาหกรรมที่ท้าทายที่สุด',
      'steel-h3':       'อุตสาหกรรมเหล็ก',
      'steel-p':        'โซ่ลำเลียงและขับเคลื่อนรับโหลดสูงสำหรับโรงงานเหล็กและโรงงานแปรรูป',
      'cement-h3':      'อุตสาหกรรมซีเมนต์',
      'cement-p':       'โซ่ทนการสึกหรอสำหรับระบบขับเคลื่อนเตาเผาและระบบขนถ่ายซีเมนต์จำนวนมาก',
      'palm-h3':        'อุตสาหกรรมน้ำมันปาล์ม',
      'palm-p':         'โซ่เกรดอาหารและทนการกัดกร่อนสำหรับการสีและแปรรูปน้ำมันปาล์ม',
      'sugar-h3':       'อุตสาหกรรมน้ำตาล',
      'sugar-p':        'โซ่ลำเลียงอ้อยและโซ่ขนส่งแบบหนักที่ออกแบบสำหรับสภาพแวดล้อมโรงงานน้ำตาล',
      'promise-eyebrow':'คำมั่นสัญญาของเรา',
      'promise-h2':     'สร้างด้วยความแม่นยำ<br>ขับเคลื่อนด้วยความเป็นเลิศ',
      'promise-p':      'เราดำเนินการตรวจสอบคุณภาพอย่างเข้มงวดและให้บริการหลังการขายที่เชื่อถือได้ เราประสานงานกับผู้ผลิตและซัพพลายเออร์เพื่อแก้ไขปัญหาต่างๆ อย่างมีประสิทธิภาพ โดยไม่จำเป็นต้องส่งวิศวกรไปยังไซต์งานในต่างประเทศ',
      'promise-btn':    'เรียนรู้เพิ่มเติมเกี่ยวกับเรา',
      'enq-eyebrow':    'ติดต่อเรา',
      'enq-h2':         'พร้อมอัปเกรดระบบโซ่ของคุณแล้วหรือยัง?',
      'enq-p':          'ส่งอีเมลหรือโทรหาเราโดยตรง — ทีมงานของเราตอบกลับภายในหนึ่งวันทำการ',
      'enq-email':      'ส่งอีเมลหาเรา →',
      'enq-call':       'โทร 02 286-5656',

      /* ---------- About page ---------- */
      'abt-eyebrow':        'บริษัทของเรา',
      'abt-h1':             'เกี่ยวกับ MPC',
      'abt-sub':            'วิศวกรรมที่แม่นยำ มาตรฐานระดับโลก',
      'abt-story-eyebrow':  'เรื่องราวของเรา',
      'abt-story-h2':       'สร้างด้วยความแม่นยำ<br>ขับเคลื่อนด้วยความเป็นเลิศ',
      'abt-story-p1':       'บริษัท โมชั่น พลัส คอร์ปอเรชั่น ก่อตั้งขึ้นด้วยพันธกิจเดียว: นำเทคโนโลยีโซ่อุตสาหกรรมระดับโลกมาสู่ภาคการผลิตและแปรรูปที่กำลังเติบโตอย่างรวดเร็วในเอเชียตะวันออกเฉียงใต้',
      'abt-story-p2':       'ในฐานะผู้จัดจำหน่ายที่ได้รับอนุญาตสำหรับแบรนด์โซ่ที่ได้รับการยอมรับในระดับนานาชาติสิบแบรนด์ MPC มอบมากกว่าแค่สินค้า — เราส่งมอบโซลูชันที่ออกแบบด้วยความแม่นยำ บริการหลังการขายที่น่าเชื่อถือ และความร่วมมือระยะยาว',
      'abt-story-p3':       'ทีมงานของเราทำงานร่วมกับลูกค้าตั้งแต่การส่งมอบสินค้าจนถึงการบำรุงรักษาและการสนับสนุนอย่างต่อเนื่อง',
      'abt-found-eyebrow':  'เราคือใคร',
      'abt-found-h2':       'รากฐานและปรัชญาของเรา',
      'abt-found-body':     'ก่อตั้งในปี <strong>2004</strong> บริษัท โมชั่น พลัส คอร์ปอเรชั่น ใช้เวลากว่าสองทศวรรษในการสร้างชื่อเสียงด้านความแม่นยำ ความน่าเชื่อถือ และความร่วมมือที่แท้จริง',
      'abt-key-h3':         'กุญแจสู่ความสำเร็จ',
      'abt-key-p':          'เรามุ่งเน้นการส่งมอบโซลูชันที่เชื่อถือได้และมีคุณค่าสูง โดยผสานคุณภาพ ประสิทธิภาพ และสมรรถนะระยะยาว เพื่อรองรับการใช้งานอุตสาหกรรมที่หลากหลาย',
      'abt-phil-h3':        'ปรัชญาของบริษัท',
      'abt-phil-p':         'เรารับประกันคุณภาพของผลิตภัณฑ์ที่คัดสรรผ่านความมุ่งมั่นระยะยาวต่อความเป็นเลิศ',
      'abt-commit-h3':      'ความมุ่งมั่นของเรา',
      'abt-commit-p':       'เรารักษาการสื่อสารอย่างใกล้ชิดกับลูกค้าและซัพพลายเออร์ ประสานงานกับผู้ผลิตเพื่อให้มั่นใจว่าปัญหาต่างๆ ได้รับการแก้ไขอย่างมีประสิทธิภาพและเป็นมืออาชีพ',
      'abt-exp-h3':         'ประสบการณ์ &amp; โปรไฟล์บริษัท',
      'abt-as-eyebrow':     'บริการหลังการขาย',
      'abt-as-h2':          'บริการหลังการขายที่คุณไว้ใจได้',
      'abt-as-p':           'เราให้บริการหลังการขายโดยรักษาการสื่อสารอย่างใกล้ชิดกับลูกค้าและซัพพลายเออร์เพื่อช่วยแก้ไขปัญหาต่างๆ อย่างมีประสิทธิภาพ',
      'abt-brands-eyebrow': 'พันธมิตรแบรนด์',
      'abt-brands-h2':      'แบรนด์ที่ได้รับอนุญาต',
      'abt-brands-p':       'เราเป็นผู้จัดจำหน่ายที่ได้รับอนุญาตสำหรับผู้ผลิตโซ่อุตสาหกรรมระดับโลกสิบราย',
      'abt-cta-h2':         'พร้อมร่วมงานกับ MPC แล้วหรือยัง?',
      'abt-cta-p':          'ติดต่อทีมงานของเราเพื่อหารือเกี่ยวกับความต้องการของคุณ เราจะหาโซลูชันโซ่ที่เหมาะสมสำหรับการใช้งานของคุณ',
      'abt-cta-btn':        'ติดต่อเรา',
      'since-years-lbl':    'ปีแห่งความเป็นเลิศในอุตสาหกรรม',
      'since-eng-lbl':      'วิศวกรและผู้เชี่ยวชาญ',
      'since-clients-lbl':  'ลูกค้าที่ให้บริการ',
      'since-brands-lbl':   'พันธมิตรแบรนด์ระดับโลก',
      'since-tagline':      'พันธมิตรโซ่อุตสาหกรรมที่น่าเชื่อถือของเอเชียตะวันออกเฉียงใต้',
      'abt-exp-headline':   '20+ ปีแห่งความเป็นเลิศในอุตสาหกรรม',
      'abt-exp-body':       'ตั้งแต่ปี 2004 เราได้ส่งมอบโซลูชันโซ่ระดับโลกทั่วเอเชียตะวันออกเฉียงใต้ เชื่อมต่อลูกค้ากับผู้ผลิตชั้นนำระดับนานาชาติพร้อมให้การสนับสนุนในท้องถิ่นอย่างรวดเร็ว',
      'abt-exp-li1':        'เครือข่ายระดับโลก — ความร่วมมือชั้นยอดกับผู้ผลิตโซ่นานาชาติ',
      'abt-exp-li2':        'ทีมผู้เชี่ยวชาญ — วิศวกรและผู้เชี่ยวชาญด้านอุตสาหกรรม 35+ คน',
      'abt-exp-li3':        'ประวัติที่พิสูจน์แล้ว — เหล็ก น้ำตาล ซีเมนต์ และอุตสาหกรรมอาหารและเครื่องดื่ม',
      'abt-val-eyebrow':    'สิ่งที่ขับเคลื่อนเรา',
      'abt-val-h2':         'ค่านิยมหลักของเรา',
      'abt-val-intro':      'หลักการสามประการที่เป็นแนวทางทุกการตัดสินใจและความร่วมมือที่ Motion Plus Corporation',
      'abt-val-prec-h3':    'ความแม่นยำ',
      'abt-val-prec-p':     'ทุกข้อกำหนดมีความสำคัญ เราใช้มาตรฐานที่เข้มงวดในการคัดเลือกสินค้าและการประกันคุณภาพ',
      'abt-val-rel-h3':     'ความน่าเชื่อถือ',
      'abt-val-rel-p':      'โซ่ของเราได้มาจากผู้ผลิตที่มีประวัติที่พิสูจน์แล้ว เมื่อเกิดปัญหา ทีมหลังการขายของเราประสานงานอย่างรวดเร็วเพื่อลดเวลาหยุดทำงาน',
      'abt-val-part-h3':    'ความร่วมมือ',
      'abt-val-part-p':     'เราลงทุนในความสัมพันธ์ระยะยาว ทำความเข้าใจกระบวนการและเป้าหมายของคุณ เพื่อเป็นพันธมิตรที่แท้จริงในความสำเร็จของคุณ',
      'abt-as-li1':         'การสื่อสารโดยตรงและการสนับสนุนการประสานงานปัญหา',
      'abt-as-li2':         'ความร่วมมือกับผู้ผลิตและซัพพลายเออร์หลัก',
      'abt-as-li3':         'การแก้ไขอย่างมีประสิทธิภาพโดยไม่ต้องไปยังไซต์งานในต่างประเทศ',
      'abt-as-btn':         'ติดต่อทีมงานของเรา',
      'abt-partners-p':     'ผู้ผลิตโซ่ระดับโลกสิบราย — แหล่งเดียวที่น่าเชื่อถือ',
      'abt-cta-eyebrow':    'เริ่มต้นเลย',
      'abt-view-work':      'ดูผลงานของเรา',

      /* ---------- Product Representation (About page) ---------- */
      'prod-rep-eyebrow':  'สินค้าที่เราจัดจำหน่าย',
      'prod-rep-h2':       'ผลิตภัณฑ์ที่เราเป็นตัวแทน',
      'prod-rep-intro':    'โซลูชันที่ออกแบบอย่างแม่นยำจากผู้ผลิตที่ได้รับการยอมรับในระดับสากล — คัดสรรเพื่อคุณภาพ ความน่าเชื่อถือ และประสิทธิภาพที่พิสูจน์แล้ว',
      'prod-hs-origin':    'จีน',
      'prod-hs-name':      'โซ่ HS',
      'prod-hs-desc':      'โซ่ลูกกลิ้งและโซ่ลำเลียงคุณภาพสูง ผลิตตามความเผื่อพิสัยที่เข้มงวดสำหรับการใช้งานอุตสาหกรรมรับโหลดสูง',
      'prod-db-origin':    'เกาหลีใต้',
      'prod-db-name':      'โซ่ Dong Bo',
      'prod-db-desc':      'โซ่ที่มีความแม่นยำระดับโลก ออกแบบสำหรับเครื่องจักรที่ต้องการประสิทธิภาพสูงในอุตสาหกรรมเหล็ก ซีเมนต์ และแปรรูปอาหาร',
      'prod-uno-origin':   'ซีรีส์มาตรฐาน',
      'prod-uno-name':     'โซ่ลูกกลิ้ง UNO',
      'prod-uno-desc':     'โซ่ส่งกำลังมาตรฐานที่เชื่อถือได้ มอบความคุ้มค่าและประสิทธิภาพสม่ำเสมอสำหรับการลำเลียงในอุตสาหกรรมทั่วไป',
      'prod-dia-origin':   'สหรัฐอเมริกา',
      'prod-dia-name':     'Diamond Chain',
      'prod-dia-desc':     'โซ่ขับเคลื่อนและลำเลียงคุณภาพสูงสำหรับงานวิกฤต ได้รับความไว้วางใจมาตั้งแต่ปี ค.ศ. 1890',
      'prod-iwis-origin':  'เยอรมนี',
      'prod-iwis-name':    'IWIS',
      'prod-iwis-desc':    'โซ่ขับเคลื่อนที่ออกแบบอย่างแม่นยำพร้อมความเผื่อพิสัยระดับละเอียดและอายุการใช้งานยาวนาน',
      'prod-kmh-origin':   'เยอรมนี',
      'prod-kmh-name':     'KMH',
      'prod-kmh-desc':     'โซลูชันท่อมาตรฐานและแบบสั่งทำพิเศษระดับอุตสาหกรรม ออกแบบสำหรับความพอดีที่แม่นยำ',
      'prod-belt-origin':  'ซีรีส์อุตสาหกรรม',
      'prod-belt-name':    'สายพานอุตสาหกรรม',
      'prod-belt-desc':    'สายพานส่งกำลังและลำเลียงความทนทานสูง คัดสรรสำหรับการดำเนินงานอุตสาหกรรมต่อเนื่อง',
      'prod-bear-origin':  'หลายแบรนด์',
      'prod-bear-name':    'แบริ่งของแท้',
      'prod-bear-desc':    'แบริ่งของแท้จากผู้ผลิตระดับสากล — ตรวจสอบได้ครบถ้วน รับรองคุณภาพ',
      'prod-rep-btn':      'ขอแคตาล็อกสินค้า',

      /* ---------- Portfolio page ---------- */
      'port-eyebrow':  'ผลงานของเรา',
      'port-h1':       'โครงการของเรา',
      'port-sub':      'โซลูชันโซ่อุตสาหกรรมในภาคส่วนที่ท้าทาย',
      'filt-all':      'ทั้งหมด',
      'filt-steel':    'เหล็ก',
      'filt-cement':   'ซีเมนต์',
      'filt-palm':     'น้ำมันปาล์ม',
      'filt-sugar':    'น้ำตาล',
      'filt-chains':   'โซ่',
      'port-cta-h2':   'มีโครงการในใจหรือไม่?',
      'port-cta-p':    'บอกเราเกี่ยวกับการใช้งานของคุณ และทีมงานของเราจะแนะนำโซลูชันโซ่ที่เหมาะสม',
      'port-cta-btn1': 'เริ่มการสนทนา',
      'port-cta-btn2': 'เรียนรู้เกี่ยวกับ MPC',
      'port-dl-eyebrow':      'เอกสาร',
      'port-dl-h2':           'ดาวน์โหลดเอกสารของเรา',
      'port-dl-intro':        'เข้าถึงโบรชัวร์สินค้าล่าสุดและโปรไฟล์บริษัทของเราสำหรับข้อมูลจำเพาะโดยละเอียด',
      'port-dl-brochure':     'ดาวน์โหลดโบรชัวร์',
      'port-dl-brochure-sub': 'ภาพรวมสินค้า &amp; ข้อมูลจำเพาะ',
      'port-dl-profile':      'ดาวน์โหลดโปรไฟล์บริษัท',
      'port-dl-profile-sub':  'ข้อมูลบริษัท (ภาษาไทย)',

      /* ---------- Contact page ---------- */
      'cont-eyebrow':    'ติดต่อเรา',
      'cont-h1':         'ติดต่อเรา',
      'cont-sub':        'มาหาโซลูชันที่เหมาะสมสำหรับอุตสาหกรรมของคุณ',
      'trust-resp':      'เวลาตอบกลับ',
      'trust-coverage':  'ครอบคลุมภูมิภาค',
      'trust-brands':    'แบรนด์ที่ได้รับอนุญาต',
      'trust-clients':   'ลูกค้าที่ให้บริการ',
      'cont-how-eyebrow':'วิธีติดต่อเรา',
      'cont-h2':         'ข้อมูลการติดต่อ',
      'cont-intro':      'ติดต่อเราโดยตรง — ทีมงานของเราพร้อมช่วยเหลือด้านการสอบถามสินค้า บริการหลังการขาย และข้อมูลทั่วไป',
      'cont-email-lbl':  'อีเมล',
      'cont-email-sub':  'เราตอบกลับภายในหนึ่งวันทำการ',
      'cont-phone-lbl':  'โทรศัพท์',
      'cont-phone-sub':  'ให้บริการในเวลาทำการ',
      'cont-fax-lbl':    'แฟกซ์',
      'cont-fax-sub':    'สำหรับการส่งเอกสาร',
      'cont-addr-lbl':   'ที่อยู่',
      'cont-hours-lbl':  'เวลาทำการ',
      'cont-social-lbl': 'ติดตามเรา',
      'cont-map-eyebrow':  'ที่ตั้งของเรา',
      'cont-map-h2':       'ค้นหาเรา',
      'cont-map-btn':      'ส่งอีเมลหาเรา',
      'cont-map-btn-gmaps':'เปิดใน Google Maps',
      'nav-email-cta':     'ส่งอีเมลหาเรา',
      'prod-eyebrow':      'สินค้าที่เราจำหน่าย',
      'prod-h1':           'สินค้าของเรา',
      'prod-sub':          'โซลูชันวิศวกรรมความแม่นยำสำหรับทุกการใช้งานอุตสาหกรรม',
      'prod-cat-eyebrow':  'หมวดหมู่สินค้า',
      'prod-cat-h2':       'เลือกดูแคตตาล็อกของเรา',
      'prod-cat-intro':    'คลิกที่หมวดหมู่เพื่อดูสินค้าที่มีจำหน่าย ติดต่อทีมงานเราสำหรับข้อมูลจำเพาะ ราคา หรือโซลูชันพิเศษ',
      'prod-cta-h':        'ต้องการสินค้าเฉพาะ?',
      'prod-cta-p':        'ติดต่อทีมงานของเราเพื่อขอข้อมูลจำเพาะ เอกสาร และราคา',
      'prod-cta-btn':      'ขอใบเสนอราคา',
      'prod-cta-email':    'ส่งอีเมลหาเรา',

      /* ======================================================
         CEMENT INDUSTRY CHAINS PAGE
      ====================================================== */
      'cem-eyebrow':      'โซ่เฉพาะอุตสาหกรรม',
      'cem-h1':           'โซ่อุตสาหกรรม<em>ซีเมนต์</em>',
      'cem-sub':          'โซ่รีเคลมเมอร์ · โซ่ยก · โซ่ลำเลียงแบบแผ่น · โซ่เครื่องฟาสเตอร์แบบสไลด์',
      'cem-badge-iso':    'รับรอง ISO9001',
      'cem-badge-severe': 'สภาวะรุนแรง',
      'cem-badge-heat':   'อุณหภูมิสูง',
      'cem-badge-proven': 'คุณภาพที่พิสูจน์แล้ว',
      'cem-bc-cat':       'โซ่เฉพาะอุตสาหกรรม',
      'cem-bc-active':    'โซ่อุตสาหกรรมซีเมนต์',
      'cem-brand-tag':    'HS Chain · อุตสาหกรรมซีเมนต์',
      'cem-s1-eyebrow':   'ภาพรวมสินค้า',
      'cem-s1-h2':        'โซ่อุตสาหกรรมซีเมนต์',
      'cem-s1-sub':       'ออกแบบพิเศษสำหรับสภาวะรุนแรงของโรงงานซีเมนต์',
      'cem-cbadge-iso':   'ISO9001',
      'cem-cbadge1':      'โซ่รีเคลมเมอร์',
      'cem-cbadge2':      'โซ่ยก',
      'cem-cbadge3':      'โซ่ลำเลียงแบบแผ่น',
      'cem-cbadge4':      'อุณหภูมิสูง',
      'cem-s1-p1':        'ด้วยประสบการณ์หลายปีและการพัฒนาอย่างต่อเนื่อง เราสามารถจัดหาโซ่รีเคลมเมอร์ โซ่ยก โซ่ลำเลียงแบบแผ่น และโซ่เครื่องฟาสเตอร์แบบสไลด์ ที่ออกแบบพิเศษสำหรับสภาวะรุนแรงของอุตสาหกรรมซีเมนต์',
      'cem-s1-p2':        'ทุกขั้นตอนของกระบวนการผลิตอยู่ภายใต้การตรวจสอบอย่างใกล้ชิดของระบบการประกันคุณภาพ ISO9001 และคุณภาพสูงพร้อมความหลากหลายของผลิตภัณฑ์ได้รับการใช้งานและยกย่องจากผู้ผลิตซีเมนต์ชื่อดังส่วนใหญ่',
      'cem-iso-title':    'การรับรองคุณภาพ ISO9001',
      'cem-iso-body':     'ทุกขั้นตอนของกระบวนการผลิตได้รับการตรวจสอบภายใต้ระบบการประกันคุณภาพ ISO9001 เพื่อให้มั่นใจในคุณภาพโซ่ที่สม่ำเสมอระดับโลก',
      'cem-s2-eyebrow':   'ช่วงผลิตภัณฑ์',
      'cem-s2-h2':        'ประเภทโซ่อุตสาหกรรมซีเมนต์',
      'cem-s2-intro':     'โซ่ครบชุดที่สร้างขึ้นเพื่อทุกขั้นตอนของการผลิตซีเมนต์ — ตั้งแต่การเรียกคืนวัตถุดิบไปจนถึงการจัดการผลิตภัณฑ์สำเร็จรูป',
      'cem-s3-eyebrow':   'ความเป็นเลิศทางวิศวกรรม',
      'cem-s3-h2':        'ทำไมต้องเลือกโซ่อุตสาหกรรมซีเมนต์ของเรา?',
      'cem-s3-intro':     'ออกแบบโดยเฉพาะสำหรับสภาวะที่ท้าทายที่สุดในโรงงานผลิตซีเมนต์สมัยใหม่ทั่วโลก',
      'cem-step1-title':  'โซ่รีเคลมเมอร์',
      'cem-step1-body':   'โซ่รีเคลมเมอร์ที่สร้างขึ้นเพื่อการกู้คืนกองวัตถุดิบ — รับแรงกดสึกหรออย่างต่อเนื่องด้วยช่วงการบำรุงรักษาขั้นต่ำ',
      'cem-step2-title':  'โซ่ยก',
      'cem-step2-body':   'โซ่ยกแบบหนักที่ออกแบบสำหรับการยกในแนวตั้งในโรงงานซีเมนต์ — ความต้านทานแรงดึงสูงพร้อมความสม่ำเสมอของระยะพิทช์ที่แม่นยำ',
      'cem-step3-title':  'โซ่ลำเลียงแบบแผ่น',
      'cem-step3-body':   'โซ่ลำเลียงแบบแผ่นที่แข็งแกร่งสำหรับการขนส่งวัสดุจำนวนมาก — ออกแบบให้ทนต่อแรงกระแทก การสึกหรอ และสภาพแวดล้อมอุณหภูมิสูง',
      'cem-step4-title':  'โซ่เครื่องฟาสเตอร์แบบสไลด์',
      'cem-step4-body':   'โซ่เครื่องฟาสเตอร์แบบสไลด์ที่มีความแม่นยำสำหรับขั้นตอนการบรรจุและการจัดการ — รักษาความแม่นยำภายใต้การทำงานต่อเนื่อง',
      'cem-step5-title':  'ระบบคุณภาพ ISO9001',
      'cem-step5-body':   'ทุกลิงค์การผลิตได้รับการตรวจสอบภายใต้ระบบการประกันคุณภาพ ISO9001 — ได้รับความไว้วางใจและยกย่องจากผู้ผลิตซีเมนต์ชื่อดังทั่วโลก',
      'cem-step6-title':  'การสนับสนุนจาก MPC ครบวงจร',
      'cem-step6-body':   'การให้คำปรึกษาทางเทคนิค การเลือกโซ่เฉพาะการใช้งาน และบริการหลังการขายทั่วเอเชียตะวันออกเฉียงใต้ผ่าน Motion Plus Corporation',
      'cem-cta-h':        'ต้องการโซลูชันโซ่อุตสาหกรรมซีเมนต์หรือไม่?',
      'cem-cta-p':        'ติดต่อทีมงานของเราสำหรับการให้คำปรึกษาทางเทคนิค ข้อมูลจำเพาะสินค้า และใบเสนอราคาที่ปรับแต่งสำหรับความต้องการโรงงานซีเมนต์ของคุณ',

      /* ======================================================
         BEARING PAGE
      ====================================================== */
      'bear-eyebrow':     'ผลิตภัณฑ์อื่นๆ',
      'bear-h1':          '<em>แบริ่ง</em>',
      'bear-sub':         'แบริ่งลูกกลิ้งแบบร่อง · แบริ่งลูกกลิ้งทรงกระบอก · แบบกรวย · แบบ Cylindrical — แบรนด์ระดับโลก',
      'bear-badge1':      'Deep Groove',
      'bear-badge2':      'แบริ่งลูกกลิ้ง',
      'bear-badge3':      'แบรนด์ระดับโลก',
      'bear-badge4':      'ทุกอุตสาหกรรม',
      'bear-bc-cat':      'อื่นๆ',
      'bear-bc-active':   'แบริ่ง',
      'bear-brand-tag':   'MPC · ผลิตภัณฑ์อื่นๆ',
      'bear-s1-eyebrow':  'ภาพรวมสินค้า',
      'bear-s1-h2':       'แบริ่ง',
      'bear-s1-sub':      'แบริ่งระดับโลกสำหรับทุกการใช้งานอุตสาหกรรม',
      'bear-cbadge1':     'Deep Groove Ball Bearing',
      'bear-cbadge2':     'Cylindrical Roller Bearing',
      'bear-cbadge3':     'Tapered Roller Bearing',
      'bear-cbadge4':     'Angular Contact',
      'bear-cbadge5':     'Spherical Roller',
      'bear-cbadge6':     'Linear Bearings',
      'bear-s1-p1':       'บริษัท โมชั่น พลัส คอร์ปอเรชั่น จัดจำหน่ายแบริ่งที่มีความแม่นยำจากผู้ผลิตที่น่าเชื่อถือที่สุดในโลก ไม่ว่าจะเป็น deep groove ball bearings สำหรับงานเบา หรือ cylindrical และ tapered roller bearings สำหรับสภาพแวดล้อมอุตสาหกรรมที่ต้องการโหลดสูง ช่วงผลิตภัณฑ์ของเราครอบคลุมทุกความต้องการ',
      'bear-s1-p2':       'เราจัดหาแบริ่งจาก SKF, FAG, TIMKEN, NTN, NSK, THK, Koyo, INA, McGILL, NB และอื่นๆ — พร้อมบริการให้คำปรึกษาทางเทคนิคเพื่อช่วยคุณเลือกประเภท ขนาด และข้อมูลจำเพาะที่เหมาะสม',
      'bear-iso-title':   'ผลิตภัณฑ์ที่ได้รับอนุญาตของแท้',
      'bear-iso-body':    'แบริ่งทั้งหมดที่จัดจำหน่ายโดย Motion Plus Corporation เป็นผลิตภัณฑ์ของแท้ที่มาจากช่องทางการจัดจำหน่ายที่ได้รับอนุญาตโดยตรง',
      'bear-s2-eyebrow':  'ช่วงผลิตภัณฑ์',
      'bear-s2-h2':       'ผลิตภัณฑ์',
      'bear-s2-intro':    'แบริ่งที่มีความแม่นยำครบชุด — ตั้งแต่ ball bearings ขนาดเล็กไปจนถึง roller bearings อุตสาหกรรมแบบหนัก — ครอบคลุมทุกขนาดและข้อกำหนดด้านโหลด',
      'bear-s3-eyebrow':  'การจัดจำหน่ายที่ได้รับอนุญาต',
      'bear-s3-h2':       'แบรนด์ที่เราจำหน่าย',
      'bear-s3-intro':    'เราจัดจำหน่ายแบริ่งของแท้จากผู้ผลิตชั้นนำของโลก — ได้รับความไว้วางใจจากวิศวกรทั่วอุตสาหกรรมที่ท้าทายที่สุดของเอเชียตะวันออกเฉียงใต้',
      'bear-s4-eyebrow':  'ทำไมต้องเลือกแบริ่ง MPC',
      'bear-s4-h2':       'ความแม่นยำ ความน่าเชื่อถือ ครอบคลุมทุกประเภท',
      'bear-s4-intro':    'ตั้งแต่แบริ่งขนาดเล็กไปจนถึงชุดอุตสาหกรรมขนาดใหญ่ — ทุกประเภทจัดจำหน่ายพร้อมการรับรองคุณภาพจากผู้ผลิตระดับโลก',
      'bear-step1-title': 'Deep Groove Ball Bearings',
      'bear-step1-body':  'ประเภทแบริ่งที่ใช้กันแพร่หลายที่สุด — มีแบบเปิด แบบมีแผ่นกั้น (ZZ) หรือแบบซีล (2RS) ครอบคลุมทุกขนาดรูเจาะมาตรฐาน',
      'bear-step2-title': 'Cylindrical Roller Bearings',
      'bear-step2-body':  'ความสามารถรับโหลดแนวรัศมีสูงสำหรับการใช้งานอุตสาหกรรมแบบหนัก — มีรูปแบบ single-row, double-row และ four-row',
      'bear-step3-title': 'Tapered Roller Bearings',
      'bear-step3-body':  'รับแรงผสมระหว่างแนวรัศมีและแนวแกน — เหมาะสำหรับเกียร์บ็อกซ์ เพลารถยนต์ และอุปกรณ์หมุนแบบหนัก',
      'bear-step4-title': 'Linear &amp; Motion Bearings',
      'bear-step4-body':  'THK และ NB linear guides, ball splines และ linear bushings สำหรับการเคลื่อนที่เชิงเส้นที่แม่นยำในเครื่องจักรอัตโนมัติและ CNC',
      'bear-step5-title': 'Angular Contact &amp; Spherical',
      'bear-step5-body':  'Angular contact ball bearings สำหรับงาน spindle ความเร็วสูง; spherical roller bearings สำหรับทนการเยื้องศูนย์ในเครื่องจักรหนัก',
      'bear-step6-title': 'การสนับสนุนจาก MPC ครบวงจร',
      'bear-step6-body':  'การเลือกแบริ่งทางเทคนิค การอ้างอิงข้าม และบริการหลังการขายทั่วเอเชียตะวันออกเฉียงใต้',
      'bear-cta-h':       'ต้องการแบริ่งสำหรับการใช้งานของคุณหรือไม่?',
      'bear-cta-p':       'ติดต่อทีมงานของเราสำหรับการเลือกทางเทคนิค การอ้างอิงข้าม เอกสาร และราคาที่แข่งขันได้สำหรับแบริ่งทุกประเภทหรือแบรนด์',

      /* ======================================================
         BELT PAGE
      ====================================================== */
      'belt-eyebrow':    'ผลิตภัณฑ์อื่นๆ',
      'belt-h1':         '<em>สายพาน</em>',
      'belt-bc-cat':     'อื่นๆ',
      'belt-bc-active':  'สายพาน',
      'belt-s1-eyebrow': 'ช่วงผลิตภัณฑ์',
      'belt-s1-h2':      'สายพาน',
      'belt-s2-eyebrow': 'การจัดจำหน่ายที่ได้รับอนุญาต',
      'belt-s2-h2':      'แบรนด์สายพานที่เราจำหน่าย',
      'belt-cta-h':      'ต้องการสายพานสำหรับการใช้งานของคุณหรือไม่?',
      'belt-cta-p':      'ติดต่อทีมงานของเราสำหรับข้อมูลจำเพาะ การอ้างอิงข้าม และราคาสำหรับสายพานทุกประเภทหรือแบรนด์',

      /* ======================================================
         COUPLING PAGE
      ====================================================== */
      'cpl-eyebrow':    'ผลิตภัณฑ์อื่นๆ',
      'cpl-h1':         '<em>คัปปลิ้ง</em>',
      'cpl-bc-cat':     'อื่นๆ',
      'cpl-bc-active':  'คัปปลิ้ง',
      'cpl-s1-eyebrow': 'ช่วงผลิตภัณฑ์',
      'cpl-s1-h2':      'คัปปลิ้ง',
      'cpl-cta-h':      'ต้องการคัปปลิ้งสำหรับการใช้งานของคุณหรือไม่?',
      'cpl-cta-p':      'ติดต่อทีมงานของเราสำหรับข้อมูลจำเพาะ การเลือก และราคาสำหรับคัปปลิ้งทุกประเภท',

      /* ======================================================
         OIL SEAL PAGE
      ====================================================== */
      'os-eyebrow':    'ผลิตภัณฑ์อื่นๆ',
      'os-h1':         '<em>ออยซีล</em>',
      'os-bc-cat':     'อื่นๆ',
      'os-bc-active':  'ออยซีล',
      'os-s1-eyebrow': 'ช่วงผลิตภัณฑ์',
      'os-s1-h2':      'ออยซีล',
      'os-cta-h':      'ต้องการออยซีลสำหรับการใช้งานของคุณหรือไม่?',
      'os-cta-p':      'ติดต่อทีมงานของเราสำหรับข้อมูลจำเพาะ การกำหนดขนาด และราคาสำหรับออยซีลทุกประเภท',

      /* ======================================================
         PE-1000 PAGE
      ====================================================== */
      'pe-eyebrow':    'ผลิตภัณฑ์อื่นๆ',
      'pe-h1':         '<em>PE-1000</em>',
      'pe-bc-cat':     'อื่นๆ',
      'pe-bc-active':  'PE-1000',
      'pe-s1-eyebrow': 'ช่วงผลิตภัณฑ์',
      'pe-s1-h2':      'PE-1000',
      'pe-cta-h':      'ต้องการชิ้นส่วน PE-1000 สำหรับการใช้งานของคุณหรือไม่?',
      'pe-cta-p':      'ติดต่อทีมงานของเราสำหรับข้อมูลจำเพาะ ขนาดที่กำหนดเอง และราคาสำหรับผลิตภัณฑ์ PE-1000',

      /* ======================================================
         SPROCKETS & PULLEY PAGE
      ====================================================== */
      'sp-eyebrow':    'ส่วนประกอบขับเคลื่อน',
      'sp-h1':         '<em>สเปรกเกต</em> &amp; พูลเล่ย์',
      'sp-bc-cat':     'สเปรกเกต &amp; พูลเล่ย์',
      'sp-bc-active':  'สเปรกเกต &amp; พูลเล่ย์',
      'sp-s1-eyebrow': 'ช่วงผลิตภัณฑ์',
      'sp-s1-h2':      'สเปรกเกต &amp; พูลเล่ย์',
      'sp-cta-h':      'ต้องการสเปรกเกตหรือพูลเล่ย์สำหรับการใช้งานของคุณหรือไม่?',
      'sp-cta-p':      'ติดต่อทีมงานของเราสำหรับข้อมูลจำเพาะทางเทคนิค รูปฟันที่กำหนดเอง และราคาที่แข่งขันได้',

      /* ======================================================
         PALM OIL CHAINS PAGE
      ====================================================== */
      'palm-pg-eyebrow':   'โซ่เฉพาะอุตสาหกรรม',
      'palm-pg-h1':        'อุตสาหกรรม<em>น้ำมันปาล์ม</em>',
      'palm-pg-sub':       'โซ่ Hollow Pin · Solid Pin · Connecting Link สำหรับการผลิตน้ำมันปาล์ม',
      'palm-bc-cat':       'โซ่เฉพาะอุตสาหกรรม',
      'palm-bc-active':    'อุตสาหกรรมน้ำมันปาล์ม',
      'palm-s1-eyebrow':   'ภาพรวมสินค้า',
      'palm-s1-h2':        'โซ่อุตสาหกรรมน้ำมันปาล์ม',
      'palm-s1-p1':        'โซ่น้ำมันปาล์มได้รับการพัฒนาจากการวิจัยประยุกต์ของเรา โดยมุ่งเน้นการปรับปรุงความน่าเชื่อถือและประสิทธิภาพในกระบวนการแปรรูปน้ำมันปาล์ม โซ่ของเราออกแบบสำหรับสายการผลิตบีบน้ำมันปาล์มที่ต้องการ — ขัดแต่งอย่างแม่นยำ ผ่านการอบความร้อน และหล่อลื่นไว้ล่วงหน้าพร้อมใช้งานทันที',
      'palm-s2-eyebrow':   'ช่วงผลิตภัณฑ์',
      'palm-s2-h2':        'ผลิตภัณฑ์โซ่น้ำมันปาล์ม',
      'palm-cta-h':        'ต้องการโซลูชันโซ่อุตสาหกรรมน้ำมันปาล์มหรือไม่?',
      'palm-cta-p':        'ติดต่อทีมงานของเราสำหรับการให้คำปรึกษาทางเทคนิค ข้อมูลจำเพาะสินค้า และใบเสนอราคาที่ปรับแต่งสำหรับความต้องการโรงงานน้ำมันปาล์มของคุณ',

      /* ======================================================
         KMH CONVEYOR PIPE PAGE
      ====================================================== */
      'kmh-pg-eyebrow':   'ผลิตภัณฑ์ KMH',
      'kmh-pg-h1':        'ท่อลำเลียง <em>KMH</em>',
      'kmh-bc-cat':       'KMH',
      'kmh-bc-active':    'ท่อลำเลียง',
      'kmh-s1-eyebrow':   'KMH · ระบบท่อ',
      'kmh-s1-h2':        'ท่อลำเลียง KMH',
      'kmh-std-label':    'ผลิตภัณฑ์มาตรฐาน',
      'kmh-std-heading':  'ผลิตภัณฑ์มาตรฐาน (ระบบท่อประสิทธิภาพสูง):<br>จากชุดก่อสร้างโมดูลาร์ KMH',
      'kmh-std-body':     'ระบบโมดูลาร์ของผลิตภัณฑ์มาตรฐานของเราประกอบด้วยผลิตภัณฑ์ที่ประสานกันอย่างสมบูรณ์หลายพันรายการ มีความยืดหยุ่นและจัดการง่าย — เลือกส่วนประกอบที่ต้องการ เชื่อมต่อกัน และคุณสามารถติดตั้งระบบที่ซับซ้อนได้อย่างรวดเร็วและง่ายดาย',
      'kmh-spc-label':    'การผลิตพิเศษ',
      'kmh-spc-heading':  'การผลิตพิเศษ (ชิ้นส่วนที่สั่งทำ):<br>ความเชี่ยวชาญพิเศษของ KMH',
      'kmh-spc-body':     'ไม่ว่าจะเป็นผลิตภัณฑ์มาตรฐานที่ปรับเปลี่ยนจากแคตาล็อกหรือการพัฒนาใหม่: ที่ที่ระบบมาตรฐานไม่เพียงพอ เราได้ "เชี่ยวชาญ" ในโซลูชันเฉพาะบุคคล การผลิตพิเศษ KMH ผลิตตามข้อกำหนดและความต้องการของคุณ และเข้ากันได้กับระบบมาตรฐาน',
      'kmh-s2-eyebrow':   'ช่วงผลิตภัณฑ์',
      'kmh-s2-h2':        'ระบบท่อลำเลียง KMH',
      'kmh-s3-eyebrow':   'ดาวน์โหลดแคตาล็อกด้านล่าง',
      'kmh-s3-h2':        'แคตาล็อกสินค้า KMH',
      'kmh-cat-title':    'KMH Produktkatalog 2023',
      'kmh-cat-meta':     'ระบบท่อประสิทธิภาพสูง · โซลูชันที่กำหนดเอง',
      'kmh-cat-btn':      'ดาวน์โหลดแคตาล็อก KMH ที่นี่',
      'kmh-cta-h':        'ต้องการโซลูชันท่อ KMH แบบกำหนดเองหรือไม่?',
      'kmh-cta-p':        'ติดต่อทีมงานของเราสำหรับข้อกำหนดโครงการ การออกแบบที่กำหนดเอง และราคาเต็ม',

      /* ======================================================
         PRODUCTS PAGE — Catalogue (accordion)
      ====================================================== */
      'prod-view-link':    'ดูสินค้า',
      /* Category titles */
      'prod-cat1-title':   'โซ่ลูกกลิ้งมาตรฐาน',
      'prod-cat1-count':   '3 แบรนด์',
      'prod-cat2-title':   'โซ่ลำเลียงและขนส่ง',
      'prod-cat2-count':   '2 แบรนด์',
      'prod-cat3-title':   'โซ่เหล็กหลอมแบบหนัก',
      'prod-cat3-count':   '1 ประเภท',
      'prod-cat4-title':   'โซ่เฉพาะอุตสาหกรรม',
      'prod-cat4-count':   '3 ภาคส่วน',
      'prod-cat5-title':   'สเปรกเกต &amp; พูลเล่ย์',
      'prod-cat5-count':   '1 ประเภท',
      'prod-cat6-title':   'อื่นๆ',
      'prod-cat6-count':   '5 ประเภท',
      'prod-cat7-title':   'KMH',
      'prod-cat7-count':   '1 ประเภท',
      /* Sub-card names & descriptions */
      'prd-uno-name':      'โซ่ UNO',
      'prd-uno-desc':      'รับรอง ISO 9001 ซีรีส์ A &amp; B แบบเส้นเดี่ยวและหลายเส้น ประหยัดต้นทุนพร้อมประสิทธิภาพระดับพรีเมียม',
      'prd-db-name':       'โซ่ Dongbo',
      'prd-db-desc':       'โซ่ลูกกลิ้งมาตรฐาน ANSI — แบบเส้นเดี่ยว คู่ และสามเส้น ผลิตในเกาหลีมากว่า 45 ปี',
      'prd-iwis-rl-name':  'โซ่ Iwis',
      'prd-iwis-rl-desc':  'โซ่ลูกกลิ้งความแม่นยำจากเยอรมนี — simplex &amp; duplex มาตรฐาน ISO 606 ปรับให้เหมาะกับไดร์ฟความเร็วสูง',
      'prd-iwis-cv-name':  'โซ่ลำเลียง Iwis',
      'prd-iwis-cv-desc':  'รุ่น attachment, double-pitch, side-bow และ hollow-pin สำหรับระบบลำเลียงที่ซับซ้อน',
      'prd-hs-cv-name':    'โซ่ลำเลียง HS',
      'prd-hs-cv-desc':    'โซ่ลำเลียงตั้งแต่รับโหลดเบาถึงหนัก สำหรับการขนส่งวัสดุในอุตสาหกรรมต่างๆ',
      'prd-forged-name':   'โซ่หลอม TRIO / โซ่หลอม UNO',
      'prd-forged-desc':   'โซ่หลอมแบบหนักคุณภาพสูง — TRIO (P.102 มม.) และ UNO (P.142 มม.) สำหรับโรงงานเหล็ก โรงซีเมนต์ &amp; โรงงานอาหารสัตว์',
      'prd-cement-name':   'อุตสาหกรรมซีเมนต์',
      'prd-cement-desc':   'โซ่รีเคลมเมอร์ โซ่ยก โซ่ลำเลียงแบบแผ่น &amp; โซ่เครื่องฟาสเตอร์แบบสไลด์ — รับรอง ISO9001 สำหรับสภาวะรุนแรงของซีเมนต์',
      'prd-sugar-name':    'อุตสาหกรรมโรงสีน้ำตาล',
      'prd-sugar-desc':    'โซ่ส่งกำลัง ยก และลำเลียงสำหรับการผลิตน้ำตาล — โซ่ป้อนชานอ้อย O-chain โซ่บุช และอื่นๆ สำหรับกระบวนการสีครบวงจร',
      'prd-palm-name':     'อุตสาหกรรมน้ำมันปาล์ม',
      'prd-palm-desc':     'โซ่ Hollow pin, Solid pin และ Connecting link ออกแบบสำหรับสายการผลิตบีบน้ำมันปาล์ม — ขัดแต่งแม่นยำ ผ่านการอบ และหล่อลื่นล่วงหน้า',
      'prd-sp-name':       'สเปรกเกต &amp; พูลเล่ย์',
      'prd-sp-desc':       'สเปรกเกตและพูลเล่ย์มาตรฐานและสั่งทำพิเศษ — สเปรกเกตโซ่ลูกกลิ้ง พูลเล่ย์ไทม์มิ่ง และชิ้นส่วนขับเคลื่อนแบบหนัก',
      'prd-bearing-name':  'แบริ่ง',
      'prd-bearing-desc':  'SKF, FAG, TIMKEN, NSK, NTN, Koyo &amp; อื่นๆ — Deep groove ball, cylindrical roller, tapered roller และ linear bearings',
      'prd-belt-name':     'สายพาน',
      'prd-belt-desc':     'สายพาน V สายพานไทม์มิ่ง และสายพานแบน สำหรับการส่งกำลังในอุตสาหกรรม',
      'prd-coupling-name': 'คัปปลิ้ง',
      'prd-coupling-desc': 'คัปปลิ้งแบบ jaw, flexible, chain และแบบแข็ง สำหรับการเชื่อมต่อเพลา',
      'prd-oilseal-name':  'ออยซีล',
      'prd-oilseal-desc':  'ออยซีลเพลาหมุนและออยซีลอุตสาหกรรม สำหรับการซีลที่เชื่อถือได้ในสภาวะที่ท้าทาย',
      'prd-pe1000-name':   'PE-1000',
      'prd-pe1000-desc':   'แผ่นกันสึก รางนำ และชิ้นส่วนที่กำหนดเองจากโพลีเอทิลีนความหนาแน่นสูง',
      'prd-kmhpipe-name':  'ท่อลำเลียง',
      'prd-kmhpipe-desc':  'ระบบท่อลำเลียงแบบปิดของ KMH รางและชิ้นส่วน สำหรับการจัดการวัสดุจำนวนมากแบบปราศจากฝุ่น',
      /* ---------- Distributor Brands section ---------- */
      'distrib-eyebrow': 'พอร์ตการจัดจำหน่าย',
      'distrib-h2':      'แบรนด์ผู้จัดจำหน่าย',
      'distrib-body':    'นอกเหนือจากแบรนด์ที่ได้รับอนุญาต เรายังจัดจำหน่ายผลิตภัณฑ์อุตสาหกรรมระดับโลกเพิ่มเติมเพื่อตอบสนองความต้องการการผลิตของคุณอย่างครบครัน',

      /* ---------- Our House Brand section ---------- */
      'hb-eyebrow':      'ผลิตภัณฑ์ของบริษัท',
      'hb-h2':           'แบรนด์ของเรา',
      'hb-body':         'โซ่ที่ออกแบบอย่างแม่นยำภายใต้มาตรฐาน MPC — แบรนด์ของบริษัทที่ออกแบบสำหรับการใช้งานหนักที่ต้องการมากที่สุด',
      'hb-view-btn':     'ดูสินค้า',
      'hb-brochure-btn': 'ดาวน์โหลดโบรชัวร์',

      /* Footer badges */
      'footer-badge-iso':  'ISO',
      'footer-badge-auth': 'ได้รับอนุญาต',
      'footer-badge-sea':  'SEA'
    },

    /* ============================================================
       KHMER (CAMBODIAN) TRANSLATIONS
    ============================================================ */
    km: {
      /* ---------- Common ---------- */
      'ann-text':           'អ្នកចែកចាយដែលមានការអនុញ្ញាត &amp; អ្នកផ្តល់សេវាក្រោយការលក់សម្រាប់ដំណោះស្រាយខ្សែច្រងឧស្សាហកម្ម',
      'ann-link':           'សួរព័ត៌មាន →',
      'nav-home':           'ទំព័រដើម',
      'nav-about':          'អំពីយើង',
      'nav-portfolio':      'ស្នាដៃ',
      'nav-products':       'ផលិតផលរបស់យើង',
      'nav-contact':        'ទំនាក់ទំនង',
      'nav-quote':          'សុំតម្លៃ',
      'btn-email':          'ផ្ញើអ៊ីមែលមកយើង',
      'back-to-products':   'ត្រឡប់ទៅផលិតផល',
      'footer-about-text':  'អ្នកចែកចាយដែលមានការអនុញ្ញាត &amp; អ្នកផ្តល់សេវាក្រោយការលក់សម្រាប់ដំណោះស្រាយខ្សែច្រងឧស្សាហកម្មនៅទូទាំងអាស៊ីអាគ្នេយ៍',
      'footer-solutions-h': 'ដំណោះស្រាយ',
      'footer-roller':      'ខ្សែច្រងរំកិល',
      'footer-conveyor':    'ខ្សែច្រងដឹកជញ្ជូន',
      'footer-escalator':   'ខ្សែច្រងជណ្ដើរ',
      'footer-drive':       'ខ្សែច្រងដើរ',
      'footer-support':     'សេវាក្រោយការលក់',
      'footer-brands-h':    'ម៉ាករបស់យើង',
      'footer-company-h':   'ក្រុមហ៊ុន',
      'footer-about-mpc':   'អំពី MPC',
      'footer-portfolio':   'ស្នាដៃ',
      'footer-contact-us':  'ទំនាក់ទំនងយើង',
      'footer-get-quote':   'សុំតម្លៃ',
      'footer-contact-h':   'ទំនាក់ទំនង',
      'footer-addr-lbl':    'អាសយដ្ឋាន',
      'footer-tel-lbl':     'ទូរស័ព្ទ',
      'footer-email-lbl':   'អ៊ីមែល',
      'footer-hours-lbl':   'ម៉ោងធ្វើការ',
      'footer-mon-fri':     'ច. – សុ.',
      'footer-sat':         'សៅរ៍',
      'footer-copyright':   '&copy; 2026 Motion Plus Corporation. រក្សាសិទ្ធិគ្រប់យ៉ាង',
      'footer-copy':        '&copy; 2026 Motion Plus Corporation Co., Ltd. រក្សាសិទ្ធិគ្រប់យ៉ាង',
      'footer-privacy':     'គោលការណ៍ភាពឯកជន',
      'footer-terms':       'លក្ខខណ្ឌសេវា',

      /* ---------- Index ---------- */
      'hero-eyebrow':   'ដំណោះស្រាយខ្សែច្រងឧស្សាហកម្ម',
      'hero-h1':        'ខ្សែច្រងល្អិតពិតប្រាកដ<br><span>ប្រសិទ្ធភាព</span>ថ្នាក់ពិភពលោក',
      'hero-sub':       'ក្រុមហ៊ុន Motion Plus Corporation គឺជាអ្នកចែកចាយដែលមានការអនុញ្ញាត និងអ្នកផ្តល់សេវាក្រោយការលក់សម្រាប់ដំណោះស្រាយខ្សែច្រងឧស្សាហកម្មពិសេសនៅទូទាំងអាស៊ីអាគ្នេយ៍',
      'hero-btn-view':  'មើលស្នាដៃរបស់យើង',
      'hero-btn-quote': 'សុំតម្លៃ',
      'stat-years-lbl': 'ឆ្នាំបទពិសោធន៍',
      'stat-brands-lbl':'ម៉ាកពិសេស',
      'stat-clients-lbl':'អតិថិជនបានបម្រើ',
      'stat-ind-lbl':   'ឧស្សាហកម្ម',
      'sbar-years':     'ឆ្នាំបទពិសោធន៍',
      'sbar-brands':    'ម៉ាកដែលមានការអនុញ្ញាត',
      'sbar-clients':   'អតិថិជនបានបម្រើ',
      'sbar-ind':       'ឧស្សាហកម្មសំខាន់',
      'cert-iso':       'ទទួលបានវិញ្ញាបនបត្រ ISO',
      'cert-dist':      'អ្នកចែកចាយដែលមានការអនុញ្ញាត',
      'cert-as':        'សេវាក្រោយការលក់',
      'cert-sea':       'គ្របដណ្ដប់ SEA',
      'esc-eyebrow':    'ម៉ាកផ្ទាល់ខ្លួន',
      'esc-h3':         'Motion Escalator',
      'esc-body':       'ម៉ាកផ្ទាល់ខ្លួនរបស់ MPC សម្រាប់ខ្សែច្រងជំហានជណ្ដើរ និងខ្សែច្រងដើរ ដែលរចនាតាមមាតចំណាត់ EN 115 និង ASME A17.1 ត្រូវបានទទួលទុកចិត្តដោយអាជ្ញាធរដឹកជញ្ជូននៅទូទាំងអាស៊ីអាគ្នេយ៍',
      'esc-btn':        'ទទួលបានព័ត៌មានលំអិតផលិតផល',
      'brands-eyebrow': 'ដៃគូម៉ាក',
      'brands-h2':      'ម៉ាកដែលមានការអនុញ្ញាតរបស់យើង',
      'brands-body':    'យើងជាអ្នកចែកចាយដែលមានការអនុញ្ញាតសម្រាប់ក្រុមហ៊ុនផលិតខ្សែច្រងឧស្សាហកម្មថ្នាក់ពិភពលោកចំនួន ១០ ដែលនាំយកស្ដង់ដារវិស្វកម្មសកលមកកាន់ប្រតិបត្តិការ',
      'commit-eyebrow': 'បំណងប្រាថ្នារបស់យើង',
      'commit-h2':      'ការប្តេជ្ញាចិត្តរបស់យើង',
      'commit-quote':   'យើងផ្តល់ការគាំទ្រក្រោយការលក់ ដោយរក្សាទំនាក់ទំនងជិតស្និទ្ធជាមួយអតិថិជន និងអ្នកផ្គត់ផ្គង់ យើងសម្របសម្រួលជាមួយអ្នកផលិតដើម្បីដោះស្រាយបញ្ហាប្រកបដោយប្រសិទ្ធភាព — ដោយមិនចាំបាច់ទស្សនកិច្ចនៅទីតាំងអន្តរជាតិ',
      'ind-eyebrow':    'វិស័យដែលយើងបម្រើ',
      'ind-h2':         'ឧស្សាហកម្មឯកទេសរបស់យើង',
      'ind-body':       'ចាប់ពីការដំណើរការដែកធ្ងន់ ដល់ការផលិតប្រេងចំការ ដំណោះស្រាយខ្សែច្រងរបស់យើងបានបញ្ជាក់ប្រសិទ្ធភាពក្នុងបរិស្ថានឧស្សាហកម្មមានតម្រូវការបំផុត',
      'steel-h3':       'ឧស្សាហកម្មដែក',
      'steel-p':        'ខ្សែច្រងដឹក និងដើរទម្ងន់ខ្ពស់សម្រាប់រោងចក្រដែក',
      'cement-h3':      'ឧស្សាហកម្មស៊ីម៉ង់',
      'cement-p':       'ខ្សែច្រងទប់ទ្រាំការខូចខាតសម្រាប់ប្រព័ន្ធ Kiln Drive',
      'palm-h3':        'ឧស្សាហកម្មប្រេងចំការ',
      'palm-p':         'ខ្សែច្រងថ្នាក់អាហារ និងទប់ទ្រាំដំណក់ (Corrosion) សម្រាប់ការកិនប្រេងចំការ',
      'sugar-h3':       'ឧស្សាហកម្មស្ករ',
      'sugar-p':        'ខ្សែច្រងដឹកអំពៅ និងដឹកធ្ងន់ ដែលរចនាសម្រាប់បរិស្ថានរោងម៉ាស្ករ',
      'promise-eyebrow':'បំណងប្រាថ្នារបស់យើង',
      'promise-h2':     'សាងសង់ដោយភាពល្អិត<br>ដំណើរដោយភាពប្រសើរ',
      'promise-p':      'យើងធ្វើការពិនិត្យគុណភាពយ៉ាងតឹងរ៉ឹង និងផ្តល់សេវាក្រោយការលក់ (After-Sales) ដែលអាចជឿទុកចិត្ត',
      'promise-btn':    'ស្វែងយល់ About Us',
      'enq-eyebrow':    'ទំនាក់ទំនងជានិច្ច',
      'enq-h2':         'ត្រៀមខ្លួនអាប់ក្រេតប្រព័ន្ធខ្សែច្រងហើយឬនៅ?',
      'enq-p':          'ផ្ញើអ៊ីមែល ឬទូរស័ព្ទមកយើងដោយផ្ទាល់ — ក្រុមការងារឆ្លើយតបក្នុងថ្ងៃធ្វើការមួយ',
      'enq-email':      'ផ្ញើអ៊ីមែលមកយើង →',
      'enq-call':       'ហៅ 02 286-5656',

      /* ---------- About ---------- */
      'abt-eyebrow':        'ក្រុមហ៊ុនរបស់យើង',
      'abt-h1':             'អំពី MPC',
      'abt-sub':            'វិស្វកម្មល្អិតពិតប្រាកដ។ ស្ដង់ដារថ្នាក់ពិភពលោក',
      'abt-story-eyebrow':  'រឿងរ៉ាវរបស់យើង',
      'abt-story-h2':       'សាងសង់ដោយភាពល្អិត<br>ដំណើរដោយភាពប្រសើរ',
      'abt-story-p1':       'ក្រុមហ៊ុន Motion Plus Corporation ត្រូវបានបង្កើតឡើងដោយបំណងប្រាថ្នាតែមួយ: ដើម្បីនាំយកបច្ចេកវិទ្យាខ្សែច្រងឧស្សាហកម្មថ្នាក់ពិភពលោកមកកាន់វិស័យការផលិតនៅអាស៊ីអាគ្នេយ៍',
      'abt-story-p2':       'ក្នុងនាមជាអ្នកចែកចាយដែលមានការអនុញ្ញាតសម្រាប់ម៉ាកខ្សែច្រងអន្តរជាតិចំនួន ១០ MPC ផ្តល់ច្រើនជាងតែផលិតផល — យើងផ្ទេរដំណោះស្រាយដែលរចនាដោយភាពល្អិត ការគាំទ្រក្រោយការលក់ (After-Sales) ដែលអាចជឿទុកចិត្ត',
      'abt-story-p3':       'ក្រុមការងារធ្វើការជាមួយអតិថិជនចាប់ពីការដឹកជញ្ជូនផលិតផលរហូតដល់ការថែទាំ និងការគាំទ្របន្ត',
      'abt-found-eyebrow':  'យើងជានរណា',
      'abt-found-h2':       'មូលដ្ឋាន &amp; ទ្រឹស្ដីរបស់យើង',
      'abt-found-body':     'បង្កើតឡើងក្នុងឆ្នាំ <strong>2004</strong> ក្រុមហ៊ុន Motion Plus Corporation បានចំណាយពេលជាង ២ ទសវត្សក្នុងការកសាងកេរ្តិ៍ឈ្មោះល្អ ពាក់ព័ន្ធនឹងភាពល្អិតពិតប្រាកដ ភាពគួរជឿ និងភាពជាដៃគូ',
      'abt-key-h3':         'គន្លឹះជោគជ័យ',
      'abt-key-p':          'យើងផ្ដោតលើការផ្ដល់ដំណោះស្រាយដែលអាចជឿទុកចិត្ត ដែលបង្រួបបង្រួម គុណភាព ប្រសិទ្ធភាព និងប្រតិបត្តិការរយៈពេលវែង',
      'abt-phil-h3':        'ទ្រឹស្ដីរបស់ក្រុមហ៊ុន',
      'abt-phil-p':         'យើងធានាគុណភាពនៃជួររបស់ក្រុមហ៊ុនតាមរយៈការប្តេជ្ញាចិត្តរយៈពេលវែងក្នុងការប្រដ្ដៅ',
      'abt-commit-h3':      'ការប្តេជ្ញាចិត្តរបស់យើង',
      'abt-commit-p':       'យើងរក្សាទំនាក់ទំនងជិតស្និទ្ធ ប្រសានងានជាមួយអ្នកផលិតដើម្បីធ្វើឱ្យប្រាកដថាបញ្ហាត្រូវបានដោះស្រាយប្រកបដោយប្រសិទ្ធភាព',
      'abt-exp-h3':         'បទពិសោធន៍ &amp; ប្រវត្តិរូបក្រុមហ៊ុន',
      'abt-as-eyebrow':     'សេវាក្រោយការលក់',
      'abt-as-h2':          'ការគាំទ្រក្រោយការលក់ (After-Sales) ដែលអ្នកអាចទំនុកចិត្ត',
      'abt-as-p':           'យើងផ្តល់ការគាំទ្រក្រោយការលក់ (After-Sales) ដោយរក្សាការទំនាក់ទំនងជិតស្និទ្ធជាមួយអតិថិជន និងអ្នកផ្គត់ផ្គង់ ដើម្បីជួយដោះស្រាយបញ្ហាប្រកបដោយប្រសិទ្ធភាព',
      'abt-brands-eyebrow': 'ដៃគូម៉ាក',
      'abt-brands-h2':      'ម៉ាកដែលមានការអនុញ្ញាតរបស់យើង',
      'abt-brands-p':       'យើងជាអ្នកចែកចាយដែលមានការអនុញ្ញាតសម្រាប់ក្រុមហ៊ុនផលិតខ្សែច្រងឧស្សាហកម្មថ្នាក់ពិភពលោកចំនួន ១០',
      'abt-cta-h2':         'ត្រៀមខ្លួនធ្វើការជាមួយ MPC ហើយឬនៅ?',
      'abt-cta-p':          'ទំនាក់ទំនងក្រុមការងាររបស់យើងដើម្បីពិភាក្សាតម្រូវការ យើងនឹងស្វែងរកដំណោះស្រាយខ្សែច្រងត្រឹមត្រូវ',
      'abt-cta-btn':        'ទំនាក់ទំនងយើង',
      'since-years-lbl':    'ឆ្នាំនៃភាពប្រសើរក្នុងឧស្សាហកម្ម',
      'since-eng-lbl':      'វិស្វករ &amp; អ្នកជំនាញ',
      'since-clients-lbl':  'អតិថិជនបានបម្រើ',
      'since-brands-lbl':   'ដៃគូម៉ាកពិភពលោក',
      'since-tagline':      'ដៃគូខ្សែច្រងឧស្សាហកម្មដែលពឹងផ្អែកបានរបស់អាស៊ីអាគ្នេយ៍',
      'abt-exp-headline':   'ជាង ២០ ឆ្នាំនៃភាពប្រសើរក្នុងឧស្សាហកម្ម',
      'abt-exp-body':       'ចាប់ពីឆ្នាំ ២០០4 យើងបានផ្ដល់ដំណោះស្រាយខ្សែច្រងថ្នាក់ពិភពលោកនៅទូទាំងអាស៊ីអាគ្នេយ៍',
      'abt-exp-li1':        'ការចូលទៅដល់សកល — ភាពជាដៃគូចំណានជាមួយក្រុមហ៊ុនផលិតខ្សែច្រងអន្តរជាតិ',
      'abt-exp-li2':        'ក្រុមជំនាញ — វិស្វករ និងអ្នកជំនាញ ៣៥+ នាក់',
      'abt-exp-li3':        'ប្រវត្តិដែលបញ្ជាក់ — ដែក ស្ករ ស៊ីម៉ង់ &amp; ឧស្សាហកម្មអាហារ',
      'abt-val-eyebrow':    'អ្វីដែលជំរុញយើង',
      'abt-val-h2':         'គុណតម្លៃស្នូលរបស់យើង',
      'abt-val-intro':      'គោលការណ៍បីដែលណែនាំការសម្រេចចិត្ត និងភាពជាដៃគូ',
      'abt-val-prec-h3':    'ភាពល្អិតពិតប្រាកដ',
      'abt-val-prec-p':     'រាល់ការជ្រើសរើសសម្ភារៈ និងការធ្វើការទប់ស្កាត់ត្រូវបានប្រតិបត្តិតាមមាតចំណាត់ Exacting',
      'abt-val-rel-h3':     'ភាពគួរជឿ',
      'abt-val-rel-p':      'ខ្សែច្រងរបស់យើងមកពីក្រុមហ៊ុនផលិតមានប្រវត្តិដែលបញ្ជាក់ ក្រុមក្រោយការលក់ (After-Sales) ប្រតិបត្តិការយ៉ាងរហ័ស',
      'abt-val-part-h3':    'ភាពជាដៃគូ',
      'abt-val-part-p':     'យើងវិនិយោគក្នុងទំនាក់ទំនងរយៈពេលវែង ស្វែងយល់ពីដំណើរការ និងគោលដៅ ដើម្បីធ្វើជាដៃគូពិតប្រាកដ',
      'abt-as-li1':         'ការទំនាក់ទំនងផ្ទាល់ និងការគាំទ្រសម្របសម្រួលបញ្ហា',
      'abt-as-li2':         'ការផ្ដោតជាមួយអ្នកផលិត និងអ្នកផ្គត់ផ្គង់ចំបង',
      'abt-as-li3':         'ការដោះស្រាយប្រកបដោយប្រសិទ្ធភាព ដោយមិនចាំបាច់ទស្សនកិច្ចទៅអន្តរជាតិ',
      'abt-as-btn':         'ទំនាក់ទំនងក្រុមការងាររបស់យើង',
      'abt-partners-p':     'ក្រុមហ៊ុនផលិតខ្សែច្រងថ្នាក់ពិភពលោកចំនួន ១០ — ប្រភពតែមួយដ៏ជឿទុកចិត្ត',
      'abt-cta-eyebrow':    'ចាប់ផ្ដើម',
      'abt-view-work':      'មើលស្នាដៃរបស់យើង',

      /* ---------- Product Representation ---------- */
      'prod-rep-eyebrow':  'អ្វីដែលយើងផ្ដល់',
      'prod-rep-h2':       'ការតំណាងផលិតផលរបស់យើង',
      'prod-rep-intro':    'ដំណោះស្រាយដែលរចនាដោយភាពល្អិតពីក្រុមហ៊ុនផលិតដែលត្រូវបានទទួលស្គាល់ — ដែលបានកំណត់សម្រាប់គុណភាព ភាពអាចជឿ និងប្រតិបត្តិការដែលបញ្ជាក់',
      'prod-hs-origin':    'ចិន',
      'prod-hs-name':      'ខ្សែច្រង HS',
      'prod-hs-desc':      'ខ្សែច្រងរំកិល និងដឹកជញ្ជូនគុណភាពខ្ពស់ ផលិតតាមមាតចំណាត់ Exacting',
      'prod-db-origin':    'កូរ៉េខាងត្បូង',
      'prod-db-name':      'ខ្សែច្រង Dong Bo',
      'prod-db-desc':      'ខ្សែច្រងល្អិតពិភពលោក ដែលរចនាសម្រាប់ម៉ាស៊ីនទ្រទ្រង់ការអនុវត្ត',
      'prod-uno-origin':   'ស៊េរីស្ដង់ដារ',
      'prod-uno-name':     'ខ្សែច្រងរំកិល UNO',
      'prod-uno-desc':     'ខ្សែច្រងបញ្ជូនស្ដង់ដារដែលអាចជឿ ផ្ដល់ប្រតិបត្តិការ និងតម្លៃល្អ',
      'prod-dia-origin':   'សហរដ្ឋអាមេរិក',
      'prod-dia-name':     'Diamond Chain',
      'prod-dia-desc':     'ខ្សែច្រង Drive និង Conveyor គុណភាពខ្ពស់សម្រាប់ការអនុវត្តស ├ំខាន់',
      'prod-iwis-origin':  'អាល្លឺម៉ង់',
      'prod-iwis-name':    'IWIS',
      'prod-iwis-desc':    'ខ្សែច្រង Drive ដែលរចនាដោយភាពល្អិតពិតប្រាកដ មានអាយុកាលបន្ថែម',
      'prod-kmh-origin':   'អាល្លឺម៉ង់',
      'prod-kmh-name':     'KMH',
      'prod-kmh-desc':     'ដំណោះស្រាយបំពង់ស្ដង់ដារ និងតម្រូវការ ថ្នាក់ឧស្សាហកម្ម',
      'prod-belt-origin':  'ស៊េរីឧស្សាហកម្ម',
      'prod-belt-name':    'សាយ (Belt) ឧស្សាហកម្ម',
      'prod-belt-desc':    'សាយបញ្ជូនថាមពល និងដឹកជញ្ជូន ដែលមានភាពយូរអង្វែង',
      'prod-bear-origin':  'ជាច្រើនម៉ាក',
      'prod-bear-name':    'Bearings ពិតប្រាកដ',
      'prod-bear-desc':    'Bearings ពិតប្រាកដពីក្រុមហ៊ុនផលិតដែលត្រូវបានទទួលស្គាល់ — ពិនិត្យ (Traceable) និងធានាគុណភាព',
      'prod-rep-btn':      'ស្នើរគំរូ (Catalogue) ផលិតផល',

      /* ---------- Portfolio ---------- */
      'port-eyebrow':  'ស្នាដៃរបស់យើង',
      'port-h1':       'គម្រោងរបស់យើង',
      'port-sub':      'ដំណោះស្រាយខ្សែច្រងឧស្សាហកម្មនៅក្នុងវិស័យទូទៅ',
      'filt-all':      'ទាំងអស់',
      'filt-steel':    'ដែក',
      'filt-cement':   'ស៊ីម៉ង់',
      'filt-palm':     'ប្រេងចំការ',
      'filt-sugar':    'ស្ករ',
      'filt-chains':   'ខ្សែច្រង',
      'port-cta-h2':   'មានគម្រោងក្នុងចិត្ត?',
      'port-cta-p':    'ប្រាប់យើងអំពីការប្រើប្រាស់ ហើយក្រុមការងាររបស់យើងនឹងណែនាំដំណោះស្រាយខ្សែច្រងត្រឹមត្រូវ',
      'port-cta-btn1': 'ចាប់ផ្ដើមការសន្ទនា',
      'port-cta-btn2': 'ស្វែងយល់ About MPC',
      'port-dl-eyebrow':      'ធនធាន',
      'port-dl-h2':           'ទាញយក (Download) ធនធានរបស់យើង',
      'port-dl-intro':        'ចូលប្រើ Brochure ផលិតផលថ្មីបំផុត និងព័ត៌មានក្រុមហ៊ុន',
      'port-dl-brochure':     'ទាញយក Brochure',
      'port-dl-brochure-sub': 'ព័ត៌មានលំអិតផលិតផល &amp; ការជ្រើស',
      'port-dl-profile':      'ទាញយក Company Profile',
      'port-dl-profile-sub':  'ព័ត៌មានក្រុមហ៊ុន (ភាសាថៃ)',

      /* ---------- Contact ---------- */
      'cont-eyebrow':    'ទំនាក់ទំនងយើង',
      'cont-h1':         'ទំនាក់ទំនង',
      'cont-sub':        'ស្វែងរកដំណោះស្រាយត្រឹមត្រូវសម្រាប់ឧស្សាហកម្មរបស់អ្នក',
      'trust-resp':      'ពេលវេលាឆ្លើយតប',
      'trust-coverage':  'ការគ្របដណ្ដប់តំបន់',
      'trust-brands':    'ម៉ាកដែលមានការអនុញ្ញាត',
      'trust-clients':   'អតិថិជនបានបម្រើ',
      'cont-how-eyebrow':'របៀបទំនាក់ទំនងយើង',
      'cont-h2':         'ព័ត៌មានទំនាក់ទំនង',
      'cont-intro':      'ទំនាក់ទំនងយើងដោយផ្ទាល់ — ក្រុមការងារស្នើរអ្នកជំនួយលើការសួរផលិតផល សេវាក្រោយការលក់',
      'cont-email-lbl':  'អ៊ីមែល',
      'cont-email-sub':  'យើងឆ្លើយតបក្នុងថ្ងៃធ្វើការមួយ',
      'cont-phone-lbl':  'ទូរស័ព្ទ',
      'cont-phone-sub':  'ដំណើរការក្នុងម៉ោងធ្វើការ',
      'cont-fax-lbl':    'ទូរសារ',
      'cont-fax-sub':    'សម្រាប់ការបញ្ជូនឯកសារ',
      'cont-addr-lbl':   'អាសយដ្ឋាន',
      'cont-hours-lbl':  'ម៉ោងធ្វើការ',
      'cont-social-lbl': 'ភ្ជាប់ជាមួយយើង',
      'cont-map-eyebrow':  'ទីតាំងរបស់យើង',
      'cont-map-h2':       'ស្វែងរកយើង',
      'cont-map-btn':      'ផ្ញើអ៊ីមែលមកយើង',
      'cont-map-btn-gmaps':'បើក Google Maps',
      'nav-email-cta':     'ផ្ញើអ៊ីមែលមកយើង',
      'prod-eyebrow':      'អ្វីដែលយើងផ្ដល់',
      'prod-h1':           'ផលិតផលរបស់យើង',
      'prod-sub':          'ដំណោះស្រាយ Engineering ល្អិតពិតប្រាកដ សម្រាប់ការប្រើប្រាស់ឧស្សាហកម្មគ្រប់ប្រភេទ',
      'prod-cat-eyebrow':  'ជួរផលិតផល',
      'prod-cat-h2':       'ទស្សនា Catalogue របស់យើង',
      'prod-cat-intro':    'ចុចលើប្រភេទណាមួយ ដើម្បីស្វែងរកផលិតផលដែលមាន ទំនាក់ទំនងក្រុមការងារ',
      'prod-cta-h':        'ត្រូវការផលិតផលជាក់លាក់?',
      'prod-cta-p':        'ទំនាក់ទំនងក្រុមការងាររបស់យើង',
      'prod-cta-btn':      'សុំតម្លៃ',
      'prod-cta-email':    'ផ្ញើអ៊ីមែលមកយើង',

      /* ---------- Cement Industry ---------- */
      'cem-eyebrow':      'ខ្សែច្រងឧស្សាហកម្មជាក់លាក់',
      'cem-h1':           'ខ្សែច្រងឧស្សាហកម្ម<em>ស៊ីម៉ង់</em>',
      'cem-sub':          'ខ្សែច្រង Reclaimer · Hoister · Apron Conveyor · Slide Fastener Machine',
      'cem-badge-iso':    'ធានា ISO9001',
      'cem-badge-severe': 'លក្ខខណ្ឌ Severe',
      'cem-badge-heat':   'សីតុណ្ហភាពខ្ពស់',
      'cem-badge-proven': 'គុណភាពបានបញ្ជាក់',
      'cem-bc-cat':       'ខ្សែច្រងឧស្សាហកម្មជាក់លាក់',
      'cem-bc-active':    'ខ្សែច្រងឧស្សាហកម្មស៊ីម៉ង់',
      'cem-brand-tag':    'HS Chain · ឧស្សាហកម្មស៊ីម៉ង់',
      'cem-s1-eyebrow':   'ទិដ្ឋភាពទូទៅផលិតផល',
      'cem-s1-h2':        'ខ្សែច្រងឧស្សាហកម្មស៊ីម៉ង់',
      'cem-s1-sub':       'ដែលរចនាពិសេសសម្រាប់លក្ខខណ្ឌ Severe នៃរោងចក្រស៊ីម៉ង់',
      'cem-cbadge-iso':   'ISO9001',
      'cem-cbadge1':      'ខ្សែច្រង Reclaimer',
      'cem-cbadge2':      'ខ្សែច្រង Hoister',
      'cem-cbadge3':      'Apron Conveyor',
      'cem-cbadge4':      'សីតុណ្ហភាពខ្ពស់',
      'cem-s1-p1':        'ដោយបទពិសោធន៍ជាច្រើនឆ្នាំ និងការអភិវឌ្ឍជាបន្ត យើងអាចផ្ដល់ខ្សែច្រង Reclaimer, Hoister, Apron Conveyor និង Slide Fastener Machine ដែលរចនាសម្រាប់ (Severe) នៃឧស្សាហកម្មស៊ីម៉ង់',
      'cem-s1-p2':        'ការតំណែង ISO9001 ត្រួតពិនិត្យជំហានបញ្ចូលគ្នាផ្ដោតលើប្រកបដោយ (High-standard) ក្នុងឧស្សាហកម្ម',
      'cem-iso-title':    'ការធានាគុណភាព ISO9001',
      'cem-iso-body':     'ជំហានផលិតគ្រប់ជំហានត្រូវបានពិនិត្យ ក្រោម ISO9001 ដើម្បីធានាគុណភាពខ្សែច្រងថ្នាក់ពិភពលោក',
      'cem-s2-eyebrow':   'ជួរផលិតផល',
      'cem-s2-h2':        'ប្រភេទខ្សែច្រងឧស្សាហកម្មស៊ីម៉ង់',
      'cem-s2-intro':     'ខ្សែច្រងគ្រប់ជួរ ដែលផ្ដោតសម្រាប់ការផលិតស៊ីម៉ង់គ្រប់ ដំណាក់',
      'cem-s3-eyebrow':   'ភាពប្រសើររបស់ Engineering',
      'cem-s3-h2':        'ហេតុអ្វីជ្រើសរើស ខ្សែច្រងឧស្សាហកម្មស៊ីម៉ង់ (Cement Industry Chains) របស់យើង?',
      'cem-s3-intro':     'ដែលរចនាស ├ុំប័ន្ននឹង (Demanding Conditions) ចំពោះ (Modern Cement) រំឡើកវ ្ញ ​ ​ ',
      'cem-step1-title':  'ខ្សែច្រង Reclaimer',
      'cem-step1-body':   'ខ្សែច្រង Reclaimer សម្រាប់ (Raw Material Stockpile Recovery) — ស ├ំ ​ ​ ​ ​ ​ ',
      'cem-step2-title':  'ខ្សែច្រង Hoister',
      'cem-step2-body':   'ខ្សែច្រង Hoister ធ្ងន់ (Heavy-Duty) ដែលរចនាសម្រាប់ (Vertical Lifting)',
      'cem-step3-title':  'ខ្សែច្រង Apron Conveyor',
      'cem-step3-body':   'ខ្សែច្រង Apron Conveyor ខ្លាំងសម្រាប់ (Bulk Material Transport)',
      'cem-step4-title':  'ខ្សែច្រង Slide Fastener Machine',
      'cem-step4-body':   'ខ្សែច្រង Slide Fastener Machine ល្អិតសម្រាប់ (Packaging Stages)',
      'cem-step5-title':  'ប្រព័ន្ធ ISO9001',
      'cem-step5-body':   'ជំហានផលិតគ្រប់ជំហានត្រូវបាន (Monitor) ក្រោម ISO9001',
      'cem-step6-title':  'ការគាំទ្រ MPC ពេញ',
      'cem-step6-body':   'ការប្រឹក្សាបច្ចេកទេស ការជ្រើសរើសខ្សែច្រង (Application-Specific) និងការគាំទ្រ (After-Sales)',
      'cem-cta-h':        'ត្រូវការ ​ ​ ​ ​ ​ ​ ​ ​ ​ (Cement Industry Chain Solutions)?',
      'cem-cta-p':        'ទំនាក់ទំនងក្រុមការងារ',

      /* ---------- Bearing ---------- */
      'bear-eyebrow':     'ផលិតផលផ្សេងៗ',
      'bear-h1':          '<em>Bearing</em>',
      'bear-sub':         'Ball Bearings · Roller Bearings · Tapered · Cylindrical — ម៉ាកថ្នាក់ពិភពលោក',
      'bear-badge1':      'Deep Groove',
      'bear-badge2':      'Roller Bearings',
      'bear-badge3':      'ម៉ាកថ្នាក់ពិភពលោក',
      'bear-badge4':      'ឧស្សាហកម្មទាំងអស់',
      'bear-bc-cat':      'ផ្សេងៗ',
      'bear-bc-active':   'Bearing',
      'bear-brand-tag':   'MPC · ផលិតផលផ្សេងៗ',
      'bear-s1-eyebrow':  'ទិដ្ឋភាពទូទៅផលិតផល',
      'bear-s1-h2':       'Bearing',
      'bear-s1-sub':      'Bearings ថ្នាក់ពិភពលោក សម្រាប់ការប្រើប្រាស់ឧស្សាហកម្មទាំងអស់',
      'bear-cbadge1':     'Deep Groove Ball Bearing',
      'bear-cbadge2':     'Cylindrical Roller Bearing',
      'bear-cbadge3':     'Tapered Roller Bearing',
      'bear-cbadge4':     'Angular Contact',
      'bear-cbadge5':     'Spherical Roller',
      'bear-cbadge6':     'Linear Bearings',
      'bear-s1-p1':       'ក្រុមហ៊ុន Motion Plus Corporation ផ្ដល់ Bearings ល្អិតពីក្រុមហ៊ុនផលិតដែលអាចជឿ',
      'bear-s1-p2':       'យើង (Source) Bearings ពី SKF, FAG, TIMKEN, NTN, NSK, THK, Koyo, INA, McGILL, NB, — ​ ​ ​',
      'bear-iso-title':   'ផលិតផលពិតប្រាកដ ​ ​ ​ ​ ​',
      'bear-iso-body':    'Bearings ទាំងអស់ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​',
      'bear-s2-eyebrow':  'ជួរផលិតផល',
      'bear-s2-h2':       'ផលិតផល',
      'bear-s2-intro':    'Bearings ល្អិតគ្រប់ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​',
      'bear-s3-eyebrow':  'ការចែកចាយ (Authorised Distribution)',
      'bear-s3-h2':       'ម៉ាក ​ ​ ​ ​ ​ ​',
      'bear-s3-intro':    'Bearings ​ ​ ​ ​ ​ ​ ​',
      'bear-s4-eyebrow':  'ហេតុអ្វីជ្រើស MPC Bearings',
      'bear-s4-h2':       'ភាពល្អិតពិតប្រាកដ ​ ​ ​ ​ ​',
      'bear-s4-intro':    'Bearings ​ ​ ​',
      'bear-step1-title': 'Deep Groove Ball Bearings',
      'bear-step1-body':  'ប្រភេទ Bearing ​ ​',
      'bear-step2-title': 'Cylindrical Roller Bearings',
      'bear-step2-body':  'ការទ ​ ​ ​ ​ ​ ​',
      'bear-step3-title': 'Tapered Roller Bearings',
      'bear-step3-body':  'ទទួលភ ​ ​ ​ ​',
      'bear-step4-title': 'Linear &amp; Motion Bearings',
      'bear-step4-body':  'THK និង NB linear guides, ​ ​',
      'bear-step5-title': 'Angular Contact &amp; Spherical',
      'bear-step5-body':  'Angular contact ball bearings ​ ​ ​',
      'bear-step6-title': 'ការគាំទ្រ MPC ពេញ',
      'bear-step6-body':  'ការជ្រើសរើស Bearing ​ ​ ​ ​ ​',
      'bear-cta-h':       'ត្រូវការ Bearings ?',
      'bear-cta-p':       'ទំនាក់ទំនងក្រុម',

      /* ---------- Belt ---------- */
      'belt-eyebrow':    'ផលិតផលផ្សេងៗ',
      'belt-h1':         '<em>Belt</em>',
      'belt-bc-cat':     'ផ្សេងៗ',
      'belt-bc-active':  'Belt',
      'belt-s1-eyebrow': 'ជួរផលិតផល',
      'belt-s1-h2':      'Belt',
      'belt-s2-eyebrow': 'ការចែកចាយ',
      'belt-s2-h2':      'ម៉ាក Belt ​ ​ ​',
      'belt-cta-h':      'ត្រូវការ Belt ?',
      'belt-cta-p':      'ទំនាក់ទំនងក្រុម',

      /* ---------- Coupling ---------- */
      'cpl-eyebrow':    'ផលិតផលផ្សេងៗ',
      'cpl-h1':         '<em>Coupling</em>',
      'cpl-bc-cat':     'ផ្សេងៗ',
      'cpl-bc-active':  'Coupling',
      'cpl-s1-eyebrow': 'ជួរផលិតផល',
      'cpl-s1-h2':      'Coupling',
      'cpl-cta-h':      'ត្រូវការ Coupling ?',
      'cpl-cta-p':      'ទំនាក់ទំនងក្រុម',

      /* ---------- Oil Seal ---------- */
      'os-eyebrow':    'ផលិតផលផ្សេងៗ',
      'os-h1':         '<em>Oil Seal</em>',
      'os-bc-cat':     'ផ្សេងៗ',
      'os-bc-active':  'Oil Seal',
      'os-s1-eyebrow': 'ជួរផលិតផល',
      'os-s1-h2':      'Oil Seal',
      'os-cta-h':      'ត្រូវការ Oil Seal ?',
      'os-cta-p':      'ទំនាក់ទំនងក្រុម',

      /* ---------- PE-1000 ---------- */
      'pe-eyebrow':    'ផលិតផលផ្សេងៗ',
      'pe-h1':         '<em>PE-1000</em>',
      'pe-bc-cat':     'ផ្សេងៗ',
      'pe-bc-active':  'PE-1000',
      'pe-s1-eyebrow': 'ជួរផលិតផល',
      'pe-s1-h2':      'PE-1000',
      'pe-cta-h':      'ត្រូវការ PE-1000 ?',
      'pe-cta-p':      'ទំនាក់ទំនងក្រុម',

      /* ---------- Sprockets & Pulley ---------- */
      'sp-eyebrow':    'ផ្នែក Drive',
      'sp-h1':         '<em>Sprockets</em> &amp; Pulley',
      'sp-bc-cat':     'Sprockets &amp; Pulley',
      'sp-bc-active':  'Sprockets &amp; Pulley',
      'sp-s1-eyebrow': 'ជួរផលិតផល',
      'sp-s1-h2':      'Sprockets &amp; Pulley',
      'sp-cta-h':      'ត្រូវការ Sprockets ឬ Pulleys ?',
      'sp-cta-p':      'ទំនាក់ទំនងក្រុម',

      /* ---------- Palm Oil ---------- */
      'palm-pg-eyebrow':   'ខ្សែច្រងឧស្សាហកម្មជាក់លាក់',
      'palm-pg-h1':        'ឧស្សាហកម្ម<em>ប្រេងចំការ</em>',
      'palm-pg-sub':       'Hollow Pin · Solid Pin · Connecting Link',
      'palm-bc-cat':       'ខ្សែច្រងឧស្សាហកម្មជាក់លាក់',
      'palm-bc-active':    'ឧស្សាហកម្មប្រេងចំការ',
      'palm-s1-eyebrow':   'ទិដ្ឋភាពទូទៅផលិតផល',
      'palm-s1-h2':        'ខ្សែច្រងឧស្សាហកម្មប្រេងចំការ',
      'palm-s1-p1':        'ខ្សែច្រងប្រេងចំការ ​ ​ ​ ​ ​ ​',
      'palm-s2-eyebrow':   'ជួរផលិតផល',
      'palm-s2-h2':        'ផលិតផលខ្សែច្រងប្រេងចំការ',
      'palm-cta-h':        'ត្រូវការ Palm Oil Industry Chain ?',
      'palm-cta-p':        'ទំនាក់ទំនងក្រុម',

      /* ---------- KMH ---------- */
      'kmh-pg-eyebrow':   'ផលិតផល KMH',
      'kmh-pg-h1':        'Conveyor Pipe <em>KMH</em>',
      'kmh-bc-cat':       'KMH',
      'kmh-bc-active':    'Conveyor Pipe',
      'kmh-s1-eyebrow':   'KMH · ប្រព័ន្ធបំពង់',
      'kmh-s1-h2':        'KMH Conveyor Pipe',
      'kmh-std-label':    'ផលិតផលស្ដង់ដារ',
      'kmh-std-heading':  'ផលិតផលស្ដង់ដារ (High Performance Pipe Systems):',
      'kmh-std-body':     'ប្រព័ន្ធ Modular ​ ​ ​ ​ ​',
      'kmh-spc-label':    'ការផលិតជាក់លាក់',
      'kmh-spc-heading':  'ការផលិតជាក់លាក់ (Custom-Made Parts):',
      'kmh-spc-body':     'ផ្ដោតលើ (Individual Solutions) ​ ​ ​',
      'kmh-s2-eyebrow':   'ជួរផលិតផល',
      'kmh-s2-h2':        'ប្រព័ន្ធ KMH Conveyor Pipe',
      'kmh-s3-eyebrow':   'ទាញយក Catalogue ខាងក្រោម',
      'kmh-s3-h2':        'KMH Product Catalogue',
      'kmh-cat-title':    'KMH Produktkatalog 2023',
      'kmh-cat-meta':     'High Performance Pipe Systems · Custom Solutions',
      'kmh-cat-btn':      'ទាញយក KMH Catalogue ​',
      'kmh-cta-h':        'ត្រូវការ KMH Pipe Solution ?',
      'kmh-cta-p':        'ទំនាក់ទំនងក្រុម',

      /* ---------- Products Catalogue ---------- */
      'prod-view-link':    'មើលផលិតផល',
      'prod-cat1-title':   'Roller Chains ស្ដង់ដារ',
      'prod-cat1-count':   '3 ម៉ាក',
      'prod-cat2-title':   'Conveyor &amp; Transport Chains',
      'prod-cat2-count':   '2 ម៉ាក',
      'prod-cat3-title':   'Forged Chains ធ្ងន់',
      'prod-cat3-count':   '1 ប្រភេទ',
      'prod-cat4-title':   'ខ្សែច្រងឧស្សាហកម្មជាក់លាក់',
      'prod-cat4-count':   '3 វិស័យ',
      'prod-cat5-title':   'Sprockets &amp; Pulley',
      'prod-cat5-count':   '1 ប្រភេទ',
      'prod-cat6-title':   'ផ្សេងៗ',
      'prod-cat6-count':   '5 ប្រភេទ',
      'prod-cat7-title':   'KMH',
      'prod-cat7-count':   '1 ប្រភេទ',
      'prd-uno-name':      'UNO Chains',
      'prd-uno-desc':      'ទទួលបាន ISO 9001 ស៊េរី A &amp; B ​ ​',
      'prd-db-name':       'Dongbo Chains',
      'prd-db-desc':       'Roller Chains ​ ​ ANSI ​ ​ ​',
      'prd-iwis-rl-name':  'Iwis Chains',
      'prd-iwis-rl-desc':  'Roller Chains ​ ​ ​ អាល្លឺម៉ង់',
      'prd-iwis-cv-name':  'Iwis Conveyor Chains',
      'prd-iwis-cv-desc':  'Attachment, double-pitch, side-bow, hollow-pin',
      'prd-hs-cv-name':    'HS Conveyor Chains',
      'prd-hs-cv-desc':    'ខ្សែច្រង Conveyor ​ ​ ​',
      'prd-forged-name':   'Forged Chain TRIO / Forged Chain UNO',
      'prd-forged-desc':   'Forged Chains ​ ​ TRIO (P.102 mm) &amp; UNO (P.142 mm)',
      'prd-cement-name':   'ឧស្សាហកម្មស៊ីម៉ង់',
      'prd-cement-desc':   'Reclaimer, Hoister, Apron Conveyor &amp; Slide Fastener — ISO9001',
      'prd-sugar-name':    'ឧស្សាហកម្មស្ករ',
      'prd-sugar-desc':    'ខ្សែច្រង ​ ​ ​ ​',
      'prd-palm-name':     'ឧស្សាហកម្មប្រេងចំការ',
      'prd-palm-desc':     'Hollow pin, Solid pin, Connecting link',
      'prd-sp-name':       'Sprockets &amp; Pulley',
      'prd-sp-desc':       'Sprockets &amp; Pulleys ​ ​',
      'prd-bearing-name':  'Bearing',
      'prd-bearing-desc':  'SKF, FAG, TIMKEN, NSK, NTN, Koyo &amp; ​',
      'prd-belt-name':     'Belt',
      'prd-belt-desc':     'V-belts, Timing belts, Flat belts',
      'prd-coupling-name': 'Coupling',
      'prd-coupling-desc': 'Jaw, Flexible, Chain, Rigid',
      'prd-oilseal-name':  'Oil Seal',
      'prd-oilseal-desc':  'Rotary shaft &amp; Industrial oil seals',
      'prd-pe1000-name':   'PE-1000',
      'prd-pe1000-desc':   'Wear strips, Guide rails, Custom components',
      'prd-kmhpipe-name':  'Conveyor Pipe',
      'prd-kmhpipe-desc':  'KMH Enclosed pipe conveyor systems',
      'distrib-eyebrow': 'Portfolio ​ ​ ​',
      'distrib-h2':      'Distributor Brands',
      'distrib-body':    '​ ​ ​ ​ ​ ​ ​ ​',
      'hb-eyebrow':      'ផលិតផលផ្ទាល់ខ្លួន',
      'hb-h2':           'ម៉ាករបស់យើង',
      'hb-body':         'ខ្សែច្រង ​ ​ ​ MPC — ​ ​',
      'hb-view-btn':     'មើលផលិតផល',
      'hb-brochure-btn': 'ទាញយក Brochure',
      'footer-badge-iso':  'ISO',
      'footer-badge-auth': 'ដែលមានការអនុញ្ញាត',
      'footer-badge-sea':  'SEA'
    }
  };

  function apply(lang) {
    var els = document.querySelectorAll('[data-i18n]');
    for (var i = 0; i < els.length; i++) {
      var el  = els[i];
      var key = el.getAttribute('data-i18n');
      if (T[lang] && T[lang][key] !== undefined) {
        el.innerHTML = T[lang][key];
      }
    }
    /* Update active button state */
    var btns = document.querySelectorAll('.lang-btn');
    for (var j = 0; j < btns.length; j++) {
      btns[j].classList.toggle('active', btns[j].getAttribute('data-lang') === lang);
    }
    /* Persist choice */
    try { localStorage.setItem('mpc-lang', lang); } catch (e) {}
    /* Update html lang attribute */
    document.documentElement.lang = lang === 'th' ? 'th' : 'en';
  }

  /* Attach click listeners */
  function attachListeners() {
    var btns = document.querySelectorAll('.lang-btn');
    for (var i = 0; i < btns.length; i++) {
      (function (btn) {
        btn.addEventListener('click', function () {
          apply(btn.getAttribute('data-lang'));
        });
      })(btns[i]);
    }
  }

  document.addEventListener('DOMContentLoaded', function () {
    attachListeners();
    var saved = 'en';
    try { saved = localStorage.getItem('mpc-lang') || 'en'; } catch (e) {}
    apply(saved);
  });

})();
